package com.ziroom.minsu.report.house.entity;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

/**
 * 
 * <p>房源订单日接受量entity</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author bushujie
 * @since 1.0
 * @version 1.0
 */
public class HouseDayOrderAcceptNumEntity extends BaseEntity{

	/**
	 * 序列化fid
	 */
	private static final long serialVersionUID = -458895385274886479L;
	
	/**
	 * 逻辑fid
	 */
	private String fid;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_day_order_accept_num.id
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_day_order_accept_num.house_fid
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    private String houseFid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_day_order_accept_num.room_fid
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    private String roomFid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_day_order_accept_num.landlord_uid
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    private String landlordUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_day_order_accept_num.city_code
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_day_order_accept_num.city_name
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_day_order_accept_num.rent_way
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    private Integer rentWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_day_order_accept_num.lan_accept_order
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    private Integer lanAcceptOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_day_order_accept_num.statistics_date
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    private Date statisticsDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_day_order_accept_num.create_date
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_day_order_accept_num.id
     *
     * @return the value of t_house_day_order_accept_num.id
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_day_order_accept_num.id
     *
     * @param id the value for t_house_day_order_accept_num.id
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_day_order_accept_num.house_fid
     *
     * @return the value of t_house_day_order_accept_num.house_fid
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    public String getHouseFid() {
        return houseFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_day_order_accept_num.house_fid
     *
     * @param houseFid the value for t_house_day_order_accept_num.house_fid
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    public void setHouseFid(String houseFid) {
        this.houseFid = houseFid == null ? null : houseFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_day_order_accept_num.room_fid
     *
     * @return the value of t_house_day_order_accept_num.room_fid
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    public String getRoomFid() {
        return roomFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_day_order_accept_num.room_fid
     *
     * @param roomFid the value for t_house_day_order_accept_num.room_fid
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    public void setRoomFid(String roomFid) {
        this.roomFid = roomFid == null ? null : roomFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_day_order_accept_num.landlord_uid
     *
     * @return the value of t_house_day_order_accept_num.landlord_uid
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    public String getLandlordUid() {
        return landlordUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_day_order_accept_num.landlord_uid
     *
     * @param landlordUid the value for t_house_day_order_accept_num.landlord_uid
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    public void setLandlordUid(String landlordUid) {
        this.landlordUid = landlordUid == null ? null : landlordUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_day_order_accept_num.city_code
     *
     * @return the value of t_house_day_order_accept_num.city_code
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_day_order_accept_num.city_code
     *
     * @param cityCode the value for t_house_day_order_accept_num.city_code
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_day_order_accept_num.city_name
     *
     * @return the value of t_house_day_order_accept_num.city_name
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_day_order_accept_num.city_name
     *
     * @param cityName the value for t_house_day_order_accept_num.city_name
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_day_order_accept_num.rent_way
     *
     * @return the value of t_house_day_order_accept_num.rent_way
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    public Integer getRentWay() {
        return rentWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_day_order_accept_num.rent_way
     *
     * @param rentWay the value for t_house_day_order_accept_num.rent_way
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    public void setRentWay(Integer rentWay) {
        this.rentWay = rentWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_day_order_accept_num.lan_accept_order
     *
     * @return the value of t_house_day_order_accept_num.lan_accept_order
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    public Integer getLanAcceptOrder() {
        return lanAcceptOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_day_order_accept_num.lan_accept_order
     *
     * @param lanAcceptOrder the value for t_house_day_order_accept_num.lan_accept_order
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    public void setLanAcceptOrder(Integer lanAcceptOrder) {
        this.lanAcceptOrder = lanAcceptOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_day_order_accept_num.statistics_date
     *
     * @return the value of t_house_day_order_accept_num.statistics_date
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    public Date getStatisticsDate() {
        return statisticsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_day_order_accept_num.statistics_date
     *
     * @param statisticsDate the value for t_house_day_order_accept_num.statistics_date
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    public void setStatisticsDate(Date statisticsDate) {
        this.statisticsDate = statisticsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_day_order_accept_num.create_date
     *
     * @return the value of t_house_day_order_accept_num.create_date
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_day_order_accept_num.create_date
     *
     * @param createDate the value for t_house_day_order_accept_num.create_date
     *
     * @mbggenerated Tue Sep 27 10:30:16 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    
	/**
	 * @return the fid
	 */
	public String getFid() {
		return fid;
	}

	/**
	 * @param fid the fid to set
	 */
	public void setFid(String fid) {
		this.fid = fid;
	}
}