package com.ziroom.minsu.entity.cms;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

/**
 * 
 * <p>活动领取记录表</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author bushujie
 * @since 1.0
 * @version 1.0
 */
public class ActivityGroupReceiveLogEntity extends BaseEntity{
    /**
	 * 序列化id
	 */
	private static final long serialVersionUID = 2863755325658675307L;

	/**
     * 自增id
     * This field corresponds to the database column t_activity_group_receive_log.id
     *
     * @mbggenerated Thu May 25 11:59:27 CST 2017
     */
    private Integer id;

    /**
     * 逻辑fid
     * This field corresponds to the database column t_activity_group_receive_log.fid
     *
     * @mbggenerated Thu May 25 11:59:27 CST 2017
     */
    private String fid;

    /**
     * 领取者uid
     * This field corresponds to the database column t_activity_group_receive_log.uid
     *
     * @mbggenerated Thu May 25 11:59:27 CST 2017
     */
    private String uid;

    /**
     * 领取手机号
     * This field corresponds to the database column t_activity_group_receive_log.mobile
     *
     * @mbggenerated Thu May 25 11:59:27 CST 2017
     */
    private String mobile;

    /**
     * 活动组编码
     * This field corresponds to the database column t_activity_group_receive_log.group_sn
     *
     * @mbggenerated Thu May 25 11:59:27 CST 2017
     */
    private String groupSn;

    /**
     * 创建时间
     * This field corresponds to the database column t_activity_group_receive_log.create_date
     *
     * @mbggenerated Thu May 25 11:59:27 CST 2017
     */
    private Date createDate;

    /**
     * 是否删除
     * This field corresponds to the database column t_activity_group_receive_log.is_del
     *
     * @mbggenerated Thu May 25 11:59:27 CST 2017
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_group_receive_log.id
     *
     * @return the value of t_activity_group_receive_log.id
     *
     * @mbggenerated Thu May 25 11:59:27 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_group_receive_log.id
     *
     * @param id the value for t_activity_group_receive_log.id
     *
     * @mbggenerated Thu May 25 11:59:27 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_group_receive_log.fid
     *
     * @return the value of t_activity_group_receive_log.fid
     *
     * @mbggenerated Thu May 25 11:59:27 CST 2017
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_group_receive_log.fid
     *
     * @param fid the value for t_activity_group_receive_log.fid
     *
     * @mbggenerated Thu May 25 11:59:27 CST 2017
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_group_receive_log.uid
     *
     * @return the value of t_activity_group_receive_log.uid
     *
     * @mbggenerated Thu May 25 11:59:27 CST 2017
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_group_receive_log.uid
     *
     * @param uid the value for t_activity_group_receive_log.uid
     *
     * @mbggenerated Thu May 25 11:59:27 CST 2017
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_group_receive_log.mobile
     *
     * @return the value of t_activity_group_receive_log.mobile
     *
     * @mbggenerated Thu May 25 11:59:27 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_group_receive_log.mobile
     *
     * @param mobile the value for t_activity_group_receive_log.mobile
     *
     * @mbggenerated Thu May 25 11:59:27 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_group_receive_log.group_sn
     *
     * @return the value of t_activity_group_receive_log.group_sn
     *
     * @mbggenerated Thu May 25 11:59:27 CST 2017
     */
    public String getGroupSn() {
        return groupSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_group_receive_log.group_sn
     *
     * @param groupSn the value for t_activity_group_receive_log.group_sn
     *
     * @mbggenerated Thu May 25 11:59:27 CST 2017
     */
    public void setGroupSn(String groupSn) {
        this.groupSn = groupSn == null ? null : groupSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_group_receive_log.create_date
     *
     * @return the value of t_activity_group_receive_log.create_date
     *
     * @mbggenerated Thu May 25 11:59:27 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_group_receive_log.create_date
     *
     * @param createDate the value for t_activity_group_receive_log.create_date
     *
     * @mbggenerated Thu May 25 11:59:27 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_group_receive_log.is_del
     *
     * @return the value of t_activity_group_receive_log.is_del
     *
     * @mbggenerated Thu May 25 11:59:27 CST 2017
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_group_receive_log.is_del
     *
     * @param isDel the value for t_activity_group_receive_log.is_del
     *
     * @mbggenerated Thu May 25 11:59:27 CST 2017
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}