package com.ziroom.minsu.entity.cms;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

/**
 * 
 * <p>专栏商圈景点图片</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author bushujie
 * @since 1.0
 * @version 1.0
 */
public class ColumnRegionPicEntity extends BaseEntity{
    /**
	 * 序列化id
	 */
	private static final long serialVersionUID = 5117794936323361434L;

	/**
     * 主键自增id
     * This field corresponds to the database column t_column_region_pic.id
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    private Integer id;

    /**
     * 逻辑fid
     * This field corresponds to the database column t_column_region_pic.fid
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    private String fid;

    /**
     * 专栏商圈景点fid
     * This field corresponds to the database column t_column_region_pic.column_region_fid
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    private String columnRegionFid;

    /**
     * 图片类型 0：主图，1：轮播图
     * This field corresponds to the database column t_column_region_pic.pic_type
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    private Integer picType;

    /**
     * 图片基础访问地址
     * This field corresponds to the database column t_column_region_pic.pic_base_url
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    private String picBaseUrl;

    /**
     * 图片后缀
     * This field corresponds to the database column t_column_region_pic.pic_suffix
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    private String picSuffix;

    /**
     * 图片服务器唯一标示
     * This field corresponds to the database column t_column_region_pic.pic_server_uuid
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    private String picServerUuid;

    /**
     * 创建人fid
     * This field corresponds to the database column t_column_region_pic.create_fid
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    private String createFid;

    /**
     * 创建时间
     * This field corresponds to the database column t_column_region_pic.create_date
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    private Date createDate;

    /**
     * 最后更新时间
     * This field corresponds to the database column t_column_region_pic.last_modify_date
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    private Date lastModifyDate;

    /**
     * 是否删除 0：否，1：是
     * This field corresponds to the database column t_column_region_pic.is_del
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_region_pic.id
     *
     * @return the value of t_column_region_pic.id
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_region_pic.id
     *
     * @param id the value for t_column_region_pic.id
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_region_pic.fid
     *
     * @return the value of t_column_region_pic.fid
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_region_pic.fid
     *
     * @param fid the value for t_column_region_pic.fid
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_region_pic.column_region_fid
     *
     * @return the value of t_column_region_pic.column_region_fid
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    public String getColumnRegionFid() {
        return columnRegionFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_region_pic.column_region_fid
     *
     * @param columnRegionFid the value for t_column_region_pic.column_region_fid
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    public void setColumnRegionFid(String columnRegionFid) {
        this.columnRegionFid = columnRegionFid == null ? null : columnRegionFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_region_pic.pic_type
     *
     * @return the value of t_column_region_pic.pic_type
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    public Integer getPicType() {
        return picType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_region_pic.pic_type
     *
     * @param picType the value for t_column_region_pic.pic_type
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    public void setPicType(Integer picType) {
        this.picType = picType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_region_pic.pic_base_url
     *
     * @return the value of t_column_region_pic.pic_base_url
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    public String getPicBaseUrl() {
        return picBaseUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_region_pic.pic_base_url
     *
     * @param picBaseUrl the value for t_column_region_pic.pic_base_url
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    public void setPicBaseUrl(String picBaseUrl) {
        this.picBaseUrl = picBaseUrl == null ? null : picBaseUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_region_pic.pic_suffix
     *
     * @return the value of t_column_region_pic.pic_suffix
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    public String getPicSuffix() {
        return picSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_region_pic.pic_suffix
     *
     * @param picSuffix the value for t_column_region_pic.pic_suffix
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    public void setPicSuffix(String picSuffix) {
        this.picSuffix = picSuffix == null ? null : picSuffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_region_pic.pic_server_uuid
     *
     * @return the value of t_column_region_pic.pic_server_uuid
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    public String getPicServerUuid() {
        return picServerUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_region_pic.pic_server_uuid
     *
     * @param picServerUuid the value for t_column_region_pic.pic_server_uuid
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    public void setPicServerUuid(String picServerUuid) {
        this.picServerUuid = picServerUuid == null ? null : picServerUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_region_pic.create_fid
     *
     * @return the value of t_column_region_pic.create_fid
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    public String getCreateFid() {
        return createFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_region_pic.create_fid
     *
     * @param createFid the value for t_column_region_pic.create_fid
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    public void setCreateFid(String createFid) {
        this.createFid = createFid == null ? null : createFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_region_pic.create_date
     *
     * @return the value of t_column_region_pic.create_date
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_region_pic.create_date
     *
     * @param createDate the value for t_column_region_pic.create_date
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_region_pic.last_modify_date
     *
     * @return the value of t_column_region_pic.last_modify_date
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_region_pic.last_modify_date
     *
     * @param lastModifyDate the value for t_column_region_pic.last_modify_date
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_region_pic.is_del
     *
     * @return the value of t_column_region_pic.is_del
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_region_pic.is_del
     *
     * @param isDel the value for t_column_region_pic.is_del
     *
     * @mbggenerated Thu Nov 10 15:43:59 CST 2016
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}