package com.ziroom.minsu.entity.cms;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

/**
 * 
 * <p>专栏模板实体类</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author bushujie
 * @since 1.0
 * @version 1.0
 */
public class ColumnTemplateEntity extends BaseEntity{
    /**
	 * 序列化fid
	 */
	private static final long serialVersionUID = -1640728682847907960L;

	/**
     * 自增id
     * This field corresponds to the database column t_column_template.id
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    private Integer id;

    /**
     * 逻辑fid
     * This field corresponds to the database column t_column_template.fid
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    private String fid;

    /**
     * 模板名称
     * This field corresponds to the database column t_column_template.temp_name
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    private String tempName;

    /**
     * 模板地址
     * This field corresponds to the database column t_column_template.temp_url
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    private String tempUrl;

    /**
     * 模板类型 0：app，1：pc，2：app/pc
     * This field corresponds to the database column t_column_template.temp_type
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    private Integer tempType;

    /**
     * 模板状态 0：注册，1：注销
     * This field corresponds to the database column t_column_template.temp_status
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    private Integer tempStatus;

    /**
     * 模板备注
     * This field corresponds to the database column t_column_template.temp_remark
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    private String tempRemark;

    /**
     * 创建人fid
     * This field corresponds to the database column t_column_template.create_fid
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    private String createFid;

    /**
     * 创建时间
     * This field corresponds to the database column t_column_template.create_date
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    private Date createDate;

    /**
     * 最后更新时间
     * This field corresponds to the database column t_column_template.last_modify_date
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    private Date lastModifyDate;

    /**
     * 是否删除 0：否，1：是
     * This field corresponds to the database column t_column_template.is_del
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_template.id
     *
     * @return the value of t_column_template.id
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_template.id
     *
     * @param id the value for t_column_template.id
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_template.fid
     *
     * @return the value of t_column_template.fid
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_template.fid
     *
     * @param fid the value for t_column_template.fid
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_template.temp_name
     *
     * @return the value of t_column_template.temp_name
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    public String getTempName() {
        return tempName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_template.temp_name
     *
     * @param tempName the value for t_column_template.temp_name
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    public void setTempName(String tempName) {
        this.tempName = tempName == null ? null : tempName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_template.temp_url
     *
     * @return the value of t_column_template.temp_url
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    public String getTempUrl() {
        return tempUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_template.temp_url
     *
     * @param tempUrl the value for t_column_template.temp_url
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    public void setTempUrl(String tempUrl) {
        this.tempUrl = tempUrl == null ? null : tempUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_template.temp_type
     *
     * @return the value of t_column_template.temp_type
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    public Integer getTempType() {
        return tempType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_template.temp_type
     *
     * @param tempType the value for t_column_template.temp_type
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    public void setTempType(Integer tempType) {
        this.tempType = tempType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_template.temp_status
     *
     * @return the value of t_column_template.temp_status
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    public Integer getTempStatus() {
        return tempStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_template.temp_status
     *
     * @param tempStatus the value for t_column_template.temp_status
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    public void setTempStatus(Integer tempStatus) {
        this.tempStatus = tempStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_template.temp_remark
     *
     * @return the value of t_column_template.temp_remark
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    public String getTempRemark() {
        return tempRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_template.temp_remark
     *
     * @param tempRemark the value for t_column_template.temp_remark
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    public void setTempRemark(String tempRemark) {
        this.tempRemark = tempRemark == null ? null : tempRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_template.create_fid
     *
     * @return the value of t_column_template.create_fid
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    public String getCreateFid() {
        return createFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_template.create_fid
     *
     * @param createFid the value for t_column_template.create_fid
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    public void setCreateFid(String createFid) {
        this.createFid = createFid == null ? null : createFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_template.create_date
     *
     * @return the value of t_column_template.create_date
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_template.create_date
     *
     * @param createDate the value for t_column_template.create_date
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_template.last_modify_date
     *
     * @return the value of t_column_template.last_modify_date
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_template.last_modify_date
     *
     * @param lastModifyDate the value for t_column_template.last_modify_date
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_template.is_del
     *
     * @return the value of t_column_template.is_del
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_template.is_del
     *
     * @param isDel the value for t_column_template.is_del
     *
     * @mbggenerated Mon Nov 07 16:34:20 CST 2016
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}