package com.ziroom.minsu.entity.cms;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

/**
 * 
 * <p>城市专栏商圈景点推荐项目</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author bushujie
 * @since 1.0
 * @version 1.0
 */
public class ColumnRegionItemEntity extends BaseEntity{
    /**
	 * 序列化id
	 */
	private static final long serialVersionUID = -2025560277463386114L;

	/**
     * 自增id
     * This field corresponds to the database column t_column_region_item.id
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    private Integer id;

    /**
     * 逻辑fid
     * This field corresponds to the database column t_column_region_item.fid
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    private String fid;

    /**
     * 专栏商圈景点fid
     * This field corresponds to the database column t_column_region_item.column_region_fid
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    private String columnRegionFid;

    /**
     * 商圈景点推荐项目fid
     * This field corresponds to the database column t_column_region_item.region_items_fid
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    private String regionItemsFid;

    /**
     * 图标访问基础地址
     * This field corresponds to the database column t_column_region_item.icon_base_url
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    private String iconBaseUrl;

    /**
     * 图标后缀
     * This field corresponds to the database column t_column_region_item.icon_suffix
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    private String iconSuffix;

    /**
     * 图片服务器唯一标示
     * This field corresponds to the database column t_column_region_item.icon_server_uuid
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    private String iconServerUuid;
    
	/**
     * 排序字段
     */
    private Integer orderSort;

	/**
     * 创建人fid
     * This field corresponds to the database column t_column_region_item.create_fid
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    private String createFid;

    /**
     * 创建时间
     * This field corresponds to the database column t_column_region_item.create_date
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    private Date createDate;

    /**
     * 最后更新时间
     * This field corresponds to the database column t_column_region_item.last_modify_date
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    private Date lastModifyDate;

    /**
     * 是否删除 0：否，1：是
     * This field corresponds to the database column t_column_region_item.is_del
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_region_item.id
     *
     * @return the value of t_column_region_item.id
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_region_item.id
     *
     * @param id the value for t_column_region_item.id
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_region_item.fid
     *
     * @return the value of t_column_region_item.fid
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_region_item.fid
     *
     * @param fid the value for t_column_region_item.fid
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_region_item.column_region_fid
     *
     * @return the value of t_column_region_item.column_region_fid
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    public String getColumnRegionFid() {
        return columnRegionFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_region_item.column_region_fid
     *
     * @param columnRegionFid the value for t_column_region_item.column_region_fid
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    public void setColumnRegionFid(String columnRegionFid) {
        this.columnRegionFid = columnRegionFid == null ? null : columnRegionFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_region_item.region_items_fid
     *
     * @return the value of t_column_region_item.region_items_fid
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    public String getRegionItemsFid() {
        return regionItemsFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_region_item.region_items_fid
     *
     * @param regionItemsFid the value for t_column_region_item.region_items_fid
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    public void setRegionItemsFid(String regionItemsFid) {
        this.regionItemsFid = regionItemsFid == null ? null : regionItemsFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_region_item.icon_base_url
     *
     * @return the value of t_column_region_item.icon_base_url
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    public String getIconBaseUrl() {
        return iconBaseUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_region_item.icon_base_url
     *
     * @param iconBaseUrl the value for t_column_region_item.icon_base_url
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    public void setIconBaseUrl(String iconBaseUrl) {
        this.iconBaseUrl = iconBaseUrl == null ? null : iconBaseUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_region_item.icon_suffix
     *
     * @return the value of t_column_region_item.icon_suffix
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    public String getIconSuffix() {
        return iconSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_region_item.icon_suffix
     *
     * @param iconSuffix the value for t_column_region_item.icon_suffix
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    public void setIconSuffix(String iconSuffix) {
        this.iconSuffix = iconSuffix == null ? null : iconSuffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_region_item.icon_server_uuid
     *
     * @return the value of t_column_region_item.icon_server_uuid
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    public String getIconServerUuid() {
        return iconServerUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_region_item.icon_server_uuid
     *
     * @param iconServerUuid the value for t_column_region_item.icon_server_uuid
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    public void setIconServerUuid(String iconServerUuid) {
        this.iconServerUuid = iconServerUuid == null ? null : iconServerUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_region_item.create_fid
     *
     * @return the value of t_column_region_item.create_fid
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    public String getCreateFid() {
        return createFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_region_item.create_fid
     *
     * @param createFid the value for t_column_region_item.create_fid
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    public void setCreateFid(String createFid) {
        this.createFid = createFid == null ? null : createFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_region_item.create_date
     *
     * @return the value of t_column_region_item.create_date
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_region_item.create_date
     *
     * @param createDate the value for t_column_region_item.create_date
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_region_item.last_modify_date
     *
     * @return the value of t_column_region_item.last_modify_date
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_region_item.last_modify_date
     *
     * @param lastModifyDate the value for t_column_region_item.last_modify_date
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_region_item.is_del
     *
     * @return the value of t_column_region_item.is_del
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_region_item.is_del
     *
     * @param isDel the value for t_column_region_item.is_del
     *
     * @mbggenerated Thu Nov 10 15:42:55 CST 2016
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
    
    /**
	 * @return the orderSort
	 */
	public Integer getOrderSort() {
		return orderSort;
	}

	/**
	 * @param orderSort the orderSort to set
	 */
	public void setOrderSort(Integer orderSort) {
		this.orderSort = orderSort;
	}
}