package com.ziroom.minsu.entity.customer;

import com.asura.framework.base.entity.BaseEntity;

import java.util.Date;

/**
 * 
 * <p>客户相关图片信息</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author bushujie
 * @since 1.0
 * @version 1.0
 */
public class CustomerPicMsgEntity extends BaseEntity{
   
	/**
	 * 序列化id
	 */
	private static final long serialVersionUID = 4288285870371798525L;

	//自增id
    private Integer id;

    //逻辑id
    private String fid;

    //用户uid
    private String uid;
 
    //图片类型 0：证件正面照，1：证件反面照，2：手持证件照，3：用户头像, 4: 营业执照
    private Integer picType;

    //图片名称
    private String picName;

    //图片基础地址
    private String picBaseUrl;

    //图片后缀
    private String picSuffix;

    //图片服务器唯一id
    private String picServerUuid;
    
    //图片审核状态（默认是审核通过）
    private Integer auditStatus;

    //创建时间
    private Date createDate;

    //最后更新时间
    private Date lastModifyDate;

    //是否删除 0：否，1：是
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_pic_msg.id
     *
     * @return the value of t_customer_pic_msg.id
     *
     * @mbggenerated Thu Apr 21 20:22:55 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_pic_msg.id
     *
     * @param id the value for t_customer_pic_msg.id
     *
     * @mbggenerated Thu Apr 21 20:22:55 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_pic_msg.fid
     *
     * @return the value of t_customer_pic_msg.fid
     *
     * @mbggenerated Thu Apr 21 20:22:55 CST 2016
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_pic_msg.fid
     *
     * @param fid the value for t_customer_pic_msg.fid
     *
     * @mbggenerated Thu Apr 21 20:22:55 CST 2016
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_pic_msg.uid
     *
     * @return the value of t_customer_pic_msg.uid
     *
     * @mbggenerated Thu Apr 21 20:22:55 CST 2016
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_pic_msg.uid
     *
     * @param uid the value for t_customer_pic_msg.uid
     *
     * @mbggenerated Thu Apr 21 20:22:55 CST 2016
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_pic_msg.pic_type
     *
     * @return the value of t_customer_pic_msg.pic_type
     *
     * @mbggenerated Thu Apr 21 20:22:55 CST 2016
     */
    public Integer getPicType() {
        return picType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_pic_msg.pic_type
     *
     * @param picType the value for t_customer_pic_msg.pic_type
     *
     * @mbggenerated Thu Apr 21 20:22:55 CST 2016
     */
    public void setPicType(Integer picType) {
        this.picType = picType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_pic_msg.pic_name
     *
     * @return the value of t_customer_pic_msg.pic_name
     *
     * @mbggenerated Thu Apr 21 20:22:55 CST 2016
     */
    public String getPicName() {
        return picName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_pic_msg.pic_name
     *
     * @param picName the value for t_customer_pic_msg.pic_name
     *
     * @mbggenerated Thu Apr 21 20:22:55 CST 2016
     */
    public void setPicName(String picName) {
        this.picName = picName == null ? null : picName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_pic_msg.pic_base_url
     *
     * @return the value of t_customer_pic_msg.pic_base_url
     *
     * @mbggenerated Thu Apr 21 20:22:55 CST 2016
     */
    public String getPicBaseUrl() {
        return picBaseUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_pic_msg.pic_base_url
     *
     * @param picBaseUrl the value for t_customer_pic_msg.pic_base_url
     *
     * @mbggenerated Thu Apr 21 20:22:55 CST 2016
     */
    public void setPicBaseUrl(String picBaseUrl) {
        this.picBaseUrl = picBaseUrl == null ? null : picBaseUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_pic_msg.pic_suffix
     *
     * @return the value of t_customer_pic_msg.pic_suffix
     *
     * @mbggenerated Thu Apr 21 20:22:55 CST 2016
     */
    public String getPicSuffix() {
        return picSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_pic_msg.pic_suffix
     *
     * @param picSuffix the value for t_customer_pic_msg.pic_suffix
     *
     * @mbggenerated Thu Apr 21 20:22:55 CST 2016
     */
    public void setPicSuffix(String picSuffix) {
        this.picSuffix = picSuffix == null ? null : picSuffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_pic_msg.pic_server_uuid
     *
     * @return the value of t_customer_pic_msg.pic_server_uuid
     *
     * @mbggenerated Thu Apr 21 20:22:55 CST 2016
     */
    public String getPicServerUuid() {
        return picServerUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_pic_msg.pic_server_uuid
     *
     * @param picServerUuid the value for t_customer_pic_msg.pic_server_uuid
     *
     * @mbggenerated Thu Apr 21 20:22:55 CST 2016
     */
    public void setPicServerUuid(String picServerUuid) {
        this.picServerUuid = picServerUuid == null ? null : picServerUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_pic_msg.create_date
     *
     * @return the value of t_customer_pic_msg.create_date
     *
     * @mbggenerated Thu Apr 21 20:22:55 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_pic_msg.create_date
     *
     * @param createDate the value for t_customer_pic_msg.create_date
     *
     * @mbggenerated Thu Apr 21 20:22:55 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_pic_msg.last_modify_date
     *
     * @return the value of t_customer_pic_msg.last_modify_date
     *
     * @mbggenerated Thu Apr 21 20:22:55 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_pic_msg.last_modify_date
     *
     * @param lastModifyDate the value for t_customer_pic_msg.last_modify_date
     *
     * @mbggenerated Thu Apr 21 20:22:55 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_pic_msg.is_del
     *
     * @return the value of t_customer_pic_msg.is_del
     *
     * @mbggenerated Thu Apr 21 20:22:55 CST 2016
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_pic_msg.is_del
     *
     * @param isDel the value for t_customer_pic_msg.is_del
     *
     * @mbggenerated Thu Apr 21 20:22:55 CST 2016
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

	public Integer getAuditStatus() {
		return auditStatus;
	}

	public void setAuditStatus(Integer auditStatus) {
		this.auditStatus = auditStatus;
	}
    
    
}