package com.ziroom.minsu.entity.customer;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

/**
 * 
 * <p>客户基本信息</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author bushujie
 * @since 1.0
 * @version 1.0
 */
public class CustomerBaseMsgEntity extends BaseEntity{

	/**
	 * 序列化id
	 */
	private static final long serialVersionUID = 8860098583330716446L;

	//自增id
    private Integer id;

	//逻辑id
    private String uid;

	//真实姓名
    private String realName;
    
	//国家码
    private String countryCode;

	//客户手机号
    private String customerMobile;

	//性别
    private Integer customerSex;

	//生日
    private Date customerBirthday;

	//邮箱
    private String customerEmail;

	//证件类型
    private Integer idType;

	//证件号码
    private String idNo;

	//昵称
    private String nickName;

	//是否房东 0：否，1：是
    private Integer isLandlord;

	//审核状态 0：未审核，1：审核通过，2：审核未通过
    private Integer auditStatus;

	//结算方式code
    private String clearingCode;

	//租金支付方式 0:房东空间,1:房东银行卡
    private Integer rentPayment;

	//国家code
    private String nationCode;

	//省code
    private String provinceCode;

	//城市code
    private String cityCode;

	//区域code
    private String areaCode;

	//居住地详细地址
    private String resideAddr;
    
    //客户学历
    private Integer customerEdu;
    
    //客户职业
    private String customerJob;

	//联系方式是否认证 0：否，1：是
    private Integer isContactAuth;

	//身份证是否认证 0：否，1：是
    private Integer isIdentityAuth;

	//头像是否上传 0：否，1：是
    private Integer isUploadIcon;

	//创建时间
    private Date createDate;

	//最后更新时间
    private Date lastModifyDate;

	//是否删除 0：否，1：是
    private Integer isDel;

    //用户初始来源 0=其他 1=M站注册 2=M站登录 3=客户端同步
    private Integer customerSource;
    
    
	public Integer getCustomerSource() {
		return customerSource;
	}

	public void setCustomerSource(Integer customerSource) {
		this.customerSource = customerSource;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_base_msg.id
     *
     * @return the value of t_customer_base_msg.id
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_base_msg.id
     *
     * @param id the value for t_customer_base_msg.id
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_base_msg.uid
     *
     * @return the value of t_customer_base_msg.uid
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_base_msg.uid
     *
     * @param uid the value for t_customer_base_msg.uid
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_base_msg.real_name
     *
     * @return the value of t_customer_base_msg.real_name
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_base_msg.real_name
     *
     * @param realName the value for t_customer_base_msg.real_name
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_base_msg.customer_mobile
     *
     * @return the value of t_customer_base_msg.customer_mobile
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public String getCustomerMobile() {
        return customerMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_base_msg.customer_mobile
     *
     * @param customerMobile the value for t_customer_base_msg.customer_mobile
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public void setCustomerMobile(String customerMobile) {
        this.customerMobile = customerMobile == null ? null : customerMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_base_msg.customer_sex
     *
     * @return the value of t_customer_base_msg.customer_sex
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public Integer getCustomerSex() {
        return customerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_base_msg.customer_sex
     *
     * @param customerSex the value for t_customer_base_msg.customer_sex
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public void setCustomerSex(Integer customerSex) {
        this.customerSex = customerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_base_msg.customer_birthday
     *
     * @return the value of t_customer_base_msg.customer_birthday
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public Date getCustomerBirthday() {
        return customerBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_base_msg.customer_birthday
     *
     * @param customerBirthday the value for t_customer_base_msg.customer_birthday
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public void setCustomerBirthday(Date customerBirthday) {
        this.customerBirthday = customerBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_base_msg.customer_email
     *
     * @return the value of t_customer_base_msg.customer_email
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public String getCustomerEmail() {
        return customerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_base_msg.customer_email
     *
     * @param customerEmail the value for t_customer_base_msg.customer_email
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail == null ? null : customerEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_base_msg.id_type
     *
     * @return the value of t_customer_base_msg.id_type
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public Integer getIdType() {
        return idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_base_msg.id_type
     *
     * @param idType the value for t_customer_base_msg.id_type
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public void setIdType(Integer idType) {
        this.idType = idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_base_msg.id_no
     *
     * @return the value of t_customer_base_msg.id_no
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_base_msg.id_no
     *
     * @param idNo the value for t_customer_base_msg.id_no
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_base_msg.nick_name
     *
     * @return the value of t_customer_base_msg.nick_name
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_base_msg.nick_name
     *
     * @param nickName the value for t_customer_base_msg.nick_name
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_base_msg.is_landlord
     *
     * @return the value of t_customer_base_msg.is_landlord
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public Integer getIsLandlord() {
        return isLandlord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_base_msg.is_landlord
     *
     * @param isLandlord the value for t_customer_base_msg.is_landlord
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public void setIsLandlord(Integer isLandlord) {
        this.isLandlord = isLandlord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_base_msg.audit_status
     *
     * @return the value of t_customer_base_msg.audit_status
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public Integer getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_base_msg.audit_status
     *
     * @param auditStatus the value for t_customer_base_msg.audit_status
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public void setAuditStatus(Integer auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_base_msg.clearing_code
     *
     * @return the value of t_customer_base_msg.clearing_code
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public String getClearingCode() {
        return clearingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_base_msg.clearing_code
     *
     * @param clearingCode the value for t_customer_base_msg.clearing_code
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public void setClearingCode(String clearingCode) {
        this.clearingCode = clearingCode == null ? null : clearingCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_base_msg.rent_payment
     *
     * @return the value of t_customer_base_msg.rent_payment
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public Integer getRentPayment() {
        return rentPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_base_msg.rent_payment
     *
     * @param rentPayment the value for t_customer_base_msg.rent_payment
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public void setRentPayment(Integer rentPayment) {
        this.rentPayment = rentPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_base_msg.nation_code
     *
     * @return the value of t_customer_base_msg.nation_code
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public String getNationCode() {
        return nationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_base_msg.nation_code
     *
     * @param nationCode the value for t_customer_base_msg.nation_code
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public void setNationCode(String nationCode) {
        this.nationCode = nationCode == null ? null : nationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_base_msg.province_code
     *
     * @return the value of t_customer_base_msg.province_code
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_base_msg.province_code
     *
     * @param provinceCode the value for t_customer_base_msg.province_code
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_base_msg.city_code
     *
     * @return the value of t_customer_base_msg.city_code
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_base_msg.city_code
     *
     * @param cityCode the value for t_customer_base_msg.city_code
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_base_msg.area_code
     *
     * @return the value of t_customer_base_msg.area_code
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_base_msg.area_code
     *
     * @param areaCode the value for t_customer_base_msg.area_code
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_base_msg.reside_addr
     *
     * @return the value of t_customer_base_msg.reside_addr
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public String getResideAddr() {
        return resideAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_base_msg.reside_addr
     *
     * @param resideAddr the value for t_customer_base_msg.reside_addr
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public void setResideAddr(String resideAddr) {
        this.resideAddr = resideAddr == null ? null : resideAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_base_msg.is_contact_auth
     *
     * @return the value of t_customer_base_msg.is_contact_auth
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public Integer getIsContactAuth() {
        return isContactAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_base_msg.is_contact_auth
     *
     * @param isContactAuth the value for t_customer_base_msg.is_contact_auth
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public void setIsContactAuth(Integer isContactAuth) {
        this.isContactAuth = isContactAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_base_msg.is_identity_auth
     *
     * @return the value of t_customer_base_msg.is_identity_auth
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public Integer getIsIdentityAuth() {
        return isIdentityAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_base_msg.is_identity_auth
     *
     * @param isIdentityAuth the value for t_customer_base_msg.is_identity_auth
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public void setIsIdentityAuth(Integer isIdentityAuth) {
        this.isIdentityAuth = isIdentityAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_base_msg.is_upload_icon
     *
     * @return the value of t_customer_base_msg.is_upload_icon
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public Integer getIsUploadIcon() {
        return isUploadIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_base_msg.is_upload_icon
     *
     * @param isUploadIcon the value for t_customer_base_msg.is_upload_icon
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public void setIsUploadIcon(Integer isUploadIcon) {
        this.isUploadIcon = isUploadIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_base_msg.create_date
     *
     * @return the value of t_customer_base_msg.create_date
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_base_msg.create_date
     *
     * @param createDate the value for t_customer_base_msg.create_date
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_base_msg.last_modify_date
     *
     * @return the value of t_customer_base_msg.last_modify_date
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_base_msg.last_modify_date
     *
     * @param lastModifyDate the value for t_customer_base_msg.last_modify_date
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_base_msg.is_del
     *
     * @return the value of t_customer_base_msg.is_del
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_base_msg.is_del
     *
     * @param isDel the value for t_customer_base_msg.is_del
     *
     * @mbggenerated Thu Apr 21 20:18:30 CST 2016
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
    
	/**
	 * @return the customerEdu
	 */
	public Integer getCustomerEdu() {
		return customerEdu;
	}

	/**
	 * @param customerEdu the customerEdu to set
	 */
	public void setCustomerEdu(Integer customerEdu) {
		this.customerEdu = customerEdu;
	}

	/**
	 * @return the customerJob
	 */
	public String getCustomerJob() {
		return customerJob;
	}

	/**
	 * @param customerJob the customerJob to set
	 */
	public void setCustomerJob(String customerJob) {
		this.customerJob = customerJob;
	}
	
    /**
	 * @return the countryCode
	 */
	public String getCountryCode() {
		return countryCode;
	}

	/**
	 * @param countryCode the countryCode to set
	 */
	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

}