package com.ziroom.minsu.entity.customer;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

 /**
  * 
  * <p>客户发票抬头</p>
  * 
  * <PRE>
  * <BR>	修改记录
  * <BR>-----------------------------------------------
  * <BR>	修改日期			修改人			修改内容
  * </PRE>
  * 
  * @author bushujie
  * @since 1.0
  * @version 1.0
  */
public class CustomerInvoiceTitleEntity extends BaseEntity{
	
	/**
	 * 序列化id
	 */
	private static final long serialVersionUID = -7689486874095942150L;

	//自增id
    private Integer id;

	//逻辑id
    private String fid;

	//用户uid
    private String uid;

	//发票抬头
    private String invoiceTitle;

	//创建时间
    private Date createDate;

	//最新更新时间
    private Date lastModifyDate;

	//是否删除 0：否，1：是
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_invoice_title.id
     *
     * @return the value of t_customer_invoice_title.id
     *
     * @mbggenerated Thu Apr 21 20:21:44 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_invoice_title.id
     *
     * @param id the value for t_customer_invoice_title.id
     *
     * @mbggenerated Thu Apr 21 20:21:44 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_invoice_title.fid
     *
     * @return the value of t_customer_invoice_title.fid
     *
     * @mbggenerated Thu Apr 21 20:21:44 CST 2016
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_invoice_title.fid
     *
     * @param fid the value for t_customer_invoice_title.fid
     *
     * @mbggenerated Thu Apr 21 20:21:44 CST 2016
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_invoice_title.uid
     *
     * @return the value of t_customer_invoice_title.uid
     *
     * @mbggenerated Thu Apr 21 20:21:44 CST 2016
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_invoice_title.uid
     *
     * @param uid the value for t_customer_invoice_title.uid
     *
     * @mbggenerated Thu Apr 21 20:21:44 CST 2016
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_invoice_title.invoice_title
     *
     * @return the value of t_customer_invoice_title.invoice_title
     *
     * @mbggenerated Thu Apr 21 20:21:44 CST 2016
     */
    public String getInvoiceTitle() {
        return invoiceTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_invoice_title.invoice_title
     *
     * @param invoiceTitle the value for t_customer_invoice_title.invoice_title
     *
     * @mbggenerated Thu Apr 21 20:21:44 CST 2016
     */
    public void setInvoiceTitle(String invoiceTitle) {
        this.invoiceTitle = invoiceTitle == null ? null : invoiceTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_invoice_title.create_date
     *
     * @return the value of t_customer_invoice_title.create_date
     *
     * @mbggenerated Thu Apr 21 20:21:44 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_invoice_title.create_date
     *
     * @param createDate the value for t_customer_invoice_title.create_date
     *
     * @mbggenerated Thu Apr 21 20:21:44 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_invoice_title.last_modify_date
     *
     * @return the value of t_customer_invoice_title.last_modify_date
     *
     * @mbggenerated Thu Apr 21 20:21:44 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_invoice_title.last_modify_date
     *
     * @param lastModifyDate the value for t_customer_invoice_title.last_modify_date
     *
     * @mbggenerated Thu Apr 21 20:21:44 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_invoice_title.is_del
     *
     * @return the value of t_customer_invoice_title.is_del
     *
     * @mbggenerated Thu Apr 21 20:21:44 CST 2016
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_invoice_title.is_del
     *
     * @param isDel the value for t_customer_invoice_title.is_del
     *
     * @mbggenerated Thu Apr 21 20:21:44 CST 2016
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}