package com.ziroom.minsu.entity.customer;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;
/**
 * 
 * <p>手机验证信息记录</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author bushujie
 * @since 1.0
 * @version 1.0
 */
public class SmsAuthLogEntity extends BaseEntity{
	
	/**
	 * 序列化id
	 */
	private static final long serialVersionUID = 8443726116259542199L;

	// 自增id
    private Integer id;

	// 逻辑id
    private String fid;

	// 手机号
    private String mobileNo;
    
    //验证码
    private String authCode;

	// 超时时间
    private Date timeoutDate;

	// 创建时间
    private Date createDate;

	// 最后更新时间
    private Date lastModifyDate;

	// 是否删除 0：否，1：是
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_auth_log.id
     *
     * @return the value of t_sms_auth_log.id
     *
     * @mbggenerated Thu Apr 21 21:10:29 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_auth_log.id
     *
     * @param id the value for t_sms_auth_log.id
     *
     * @mbggenerated Thu Apr 21 21:10:29 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_auth_log.fid
     *
     * @return the value of t_sms_auth_log.fid
     *
     * @mbggenerated Thu Apr 21 21:10:29 CST 2016
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_auth_log.fid
     *
     * @param fid the value for t_sms_auth_log.fid
     *
     * @mbggenerated Thu Apr 21 21:10:29 CST 2016
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_auth_log.mobile_no
     *
     * @return the value of t_sms_auth_log.mobile_no
     *
     * @mbggenerated Thu Apr 21 21:10:29 CST 2016
     */
    public String getMobileNo() {
        return mobileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_auth_log.mobile_no
     *
     * @param mobileNo the value for t_sms_auth_log.mobile_no
     *
     * @mbggenerated Thu Apr 21 21:10:29 CST 2016
     */
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo == null ? null : mobileNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_auth_log.timeout_date
     *
     * @return the value of t_sms_auth_log.timeout_date
     *
     * @mbggenerated Thu Apr 21 21:10:29 CST 2016
     */
    public Date getTimeoutDate() {
        return timeoutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_auth_log.timeout_date
     *
     * @param timeoutDate the value for t_sms_auth_log.timeout_date
     *
     * @mbggenerated Thu Apr 21 21:10:29 CST 2016
     */
    public void setTimeoutDate(Date timeoutDate) {
        this.timeoutDate = timeoutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_auth_log.create_date
     *
     * @return the value of t_sms_auth_log.create_date
     *
     * @mbggenerated Thu Apr 21 21:10:29 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_auth_log.create_date
     *
     * @param createDate the value for t_sms_auth_log.create_date
     *
     * @mbggenerated Thu Apr 21 21:10:29 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_auth_log.last_modify_date
     *
     * @return the value of t_sms_auth_log.last_modify_date
     *
     * @mbggenerated Thu Apr 21 21:10:29 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_auth_log.last_modify_date
     *
     * @param lastModifyDate the value for t_sms_auth_log.last_modify_date
     *
     * @mbggenerated Thu Apr 21 21:10:29 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_auth_log.is_del
     *
     * @return the value of t_sms_auth_log.is_del
     *
     * @mbggenerated Thu Apr 21 21:10:29 CST 2016
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_auth_log.is_del
     *
     * @param isDel the value for t_sms_auth_log.is_del
     *
     * @mbggenerated Thu Apr 21 21:10:29 CST 2016
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
    
    /**
	 * @return the authCode
	 */
	public String getAuthCode() {
		return authCode;
	}

	/**
	 * @param authCode the authCode to set
	 */
	public void setAuthCode(String authCode) {
		this.authCode = authCode;
	}
}