package com.ziroom.minsu.entity.file;


import com.asura.framework.base.entity.BaseEntity;

import java.util.Date;
/**
 * 
 * <p>城市档案</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author bushujie
 * @since 1.0
 * @version 1.0
 */
public class FileCityEntity extends BaseEntity{

    private static final long serialVersionUID = 6442587622263977107L;

    /**
     * 自增id
     * @mbggenerated Mon Nov 07 14:21:34 CST 2016
     */
    private Integer id;

    /**
     * 逻辑fid
     * @mbggenerated Mon Nov 07 14:21:34 CST 2016
     */
    private String fid;

    /**
     * 城市code
     * @mbggenerated Mon Nov 07 14:21:34 CST 2016
     */
    private String cityCode;

    /**
     * 创建人fid
     * @mbggenerated Mon Nov 07 14:21:34 CST 2016
     */
    private String createFid;

    /**
     * 创建时间
     * @mbggenerated Mon Nov 07 14:21:34 CST 2016
     */
    private Date createDate;

    /**
     * 最后修改时间
     * @mbggenerated Mon Nov 07 14:21:34 CST 2016
     */
    private Date lastModifyDate;

    /**
     * 是否删除 0：否，1：是
     * @mbggenerated Mon Nov 07 14:21:34 CST 2016
     */
    private Integer isDel;

    /**
     * 城市档案内容
     * @mbggenerated Mon Nov 07 14:21:34 CST 2016
     */
    private String cityFileContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_city.id
     *
     * @return the value of t_file_city.id
     *
     * @mbggenerated Mon Nov 07 14:21:34 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_city.id
     *
     * @param id the value for t_file_city.id
     *
     * @mbggenerated Mon Nov 07 14:21:34 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_city.fid
     *
     * @return the value of t_file_city.fid
     *
     * @mbggenerated Mon Nov 07 14:21:34 CST 2016
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_city.fid
     *
     * @param fid the value for t_file_city.fid
     *
     * @mbggenerated Mon Nov 07 14:21:34 CST 2016
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_city.city_code
     *
     * @return the value of t_file_city.city_code
     *
     * @mbggenerated Mon Nov 07 14:21:34 CST 2016
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_city.city_code
     *
     * @param cityCode the value for t_file_city.city_code
     *
     * @mbggenerated Mon Nov 07 14:21:34 CST 2016
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_city.create_fid
     *
     * @return the value of t_file_city.create_fid
     *
     * @mbggenerated Mon Nov 07 14:21:34 CST 2016
     */
    public String getCreateFid() {
        return createFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_city.create_fid
     *
     * @param createFid the value for t_file_city.create_fid
     *
     * @mbggenerated Mon Nov 07 14:21:34 CST 2016
     */
    public void setCreateFid(String createFid) {
        this.createFid = createFid == null ? null : createFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_city.create_date
     *
     * @return the value of t_file_city.create_date
     *
     * @mbggenerated Mon Nov 07 14:21:34 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_city.create_date
     *
     * @param createDate the value for t_file_city.create_date
     *
     * @mbggenerated Mon Nov 07 14:21:34 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_city.last_modify_date
     *
     * @return the value of t_file_city.last_modify_date
     *
     * @mbggenerated Mon Nov 07 14:21:34 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_city.last_modify_date
     *
     * @param lastModifyDate the value for t_file_city.last_modify_date
     *
     * @mbggenerated Mon Nov 07 14:21:34 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_city.is_del
     *
     * @return the value of t_file_city.is_del
     *
     * @mbggenerated Mon Nov 07 14:21:34 CST 2016
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_city.is_del
     *
     * @param isDel the value for t_file_city.is_del
     *
     * @mbggenerated Mon Nov 07 14:21:34 CST 2016
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_city.city_file_content
     *
     * @return the value of t_file_city.city_file_content
     *
     * @mbggenerated Mon Nov 07 14:21:34 CST 2016
     */
    public String getCityFileContent() {
        return cityFileContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_city.city_file_content
     *
     * @param cityFileContent the value for t_file_city.city_file_content
     *
     * @mbggenerated Mon Nov 07 14:21:34 CST 2016
     */
    public void setCityFileContent(String cityFileContent) {
        this.cityFileContent = cityFileContent == null ? null : cityFileContent.trim();
    }
}