package com.ziroom.minsu.entity.file;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

/**
 * 
 * <p>商圈景点档案</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author bushujie
 * @since 1.0
 * @version 1.0
 */
public class FileRegionEntity extends BaseEntity{
    /**
	 * 序列化id
	 */
	private static final long serialVersionUID = 2992081050756873967L;

	/**
     * 自增id
     * This field corresponds to the database column t_file_region.id
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    private Integer id;

    /**
     * 逻辑fid
     * This field corresponds to the database column t_file_region.fid
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    private String fid;

    /**
     * 商圈景点fid
     * This field corresponds to the database column t_file_region.hot_region_fid
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    private String hotRegionFid;

    /**
     * 商圈景点描述
     * This field corresponds to the database column t_file_region.hot_region_brief
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    private String hotRegionBrief;

    /**
     * 创建人fid
     * This field corresponds to the database column t_file_region.create_fid
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    private String createFid;

    /**
     * 创建时间
     * This field corresponds to the database column t_file_region.create_date
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    private Date createDate;

    /**
     * 最后更新时间
     * This field corresponds to the database column t_file_region.last_modify_date
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    private Date lastModifyDate;

    /**
     * 是否删除 0：否，1：是
     * This field corresponds to the database column t_file_region.is_del
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    private Integer isDel;

    /**
     * 商圈景点档案
     * This field corresponds to the database column t_file_region.hot_region_content
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    private String hotRegionContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_region.id
     *
     * @return the value of t_file_region.id
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_region.id
     *
     * @param id the value for t_file_region.id
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_region.fid
     *
     * @return the value of t_file_region.fid
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_region.fid
     *
     * @param fid the value for t_file_region.fid
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_region.hot_region_fid
     *
     * @return the value of t_file_region.hot_region_fid
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    public String getHotRegionFid() {
        return hotRegionFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_region.hot_region_fid
     *
     * @param hotRegionFid the value for t_file_region.hot_region_fid
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    public void setHotRegionFid(String hotRegionFid) {
        this.hotRegionFid = hotRegionFid == null ? null : hotRegionFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_region.hot_region_brief
     *
     * @return the value of t_file_region.hot_region_brief
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    public String getHotRegionBrief() {
        return hotRegionBrief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_region.hot_region_brief
     *
     * @param hotRegionBrief the value for t_file_region.hot_region_brief
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    public void setHotRegionBrief(String hotRegionBrief) {
        this.hotRegionBrief = hotRegionBrief == null ? null : hotRegionBrief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_region.create_fid
     *
     * @return the value of t_file_region.create_fid
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    public String getCreateFid() {
        return createFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_region.create_fid
     *
     * @param createFid the value for t_file_region.create_fid
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    public void setCreateFid(String createFid) {
        this.createFid = createFid == null ? null : createFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_region.create_date
     *
     * @return the value of t_file_region.create_date
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_region.create_date
     *
     * @param createDate the value for t_file_region.create_date
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_region.last_modify_date
     *
     * @return the value of t_file_region.last_modify_date
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_region.last_modify_date
     *
     * @param lastModifyDate the value for t_file_region.last_modify_date
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_region.is_del
     *
     * @return the value of t_file_region.is_del
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_region.is_del
     *
     * @param isDel the value for t_file_region.is_del
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_region.hot_region_content
     *
     * @return the value of t_file_region.hot_region_content
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    public String getHotRegionContent() {
        return hotRegionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_region.hot_region_content
     *
     * @param hotRegionContent the value for t_file_region.hot_region_content
     *
     * @mbggenerated Mon Nov 07 14:23:58 CST 2016
     */
    public void setHotRegionContent(String hotRegionContent) {
        this.hotRegionContent = hotRegionContent == null ? null : hotRegionContent.trim();
    }
}