package com.ziroom.minsu.entity.file;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

 /**
  * 
  * <p>景点商圈推荐项目</p>
  * 
  * <PRE>
  * <BR>	修改记录
  * <BR>-----------------------------------------------
  * <BR>	修改日期			修改人			修改内容
  * </PRE>
  * 
  * @author bushujie
  * @since 1.0
  * @version 1.0
  */
public class FileRegionItemsEntity extends BaseEntity{
    /**
	 * 序列化id
	 */
	private static final long serialVersionUID = -2232561859926016712L;

	/**
     * 自增id
     * This field corresponds to the database column t_file_region_items.id
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    private Integer id;

    /**
     * 逻辑fid
     * This field corresponds to the database column t_file_region_items.fid
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    private String fid;

    /**
     * 景点商圈fid
     * This field corresponds to the database column t_file_region_items.hot_region_fid
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    private String hotRegionFid;

    /**
     * 项目名称
     * This field corresponds to the database column t_file_region_items.item_name
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    private String itemName;

    /**
     * 项目描述
     * This field corresponds to the database column t_file_region_items.item_brief
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    private String itemBrief;

    /**
     * 项目摘要
     * This field corresponds to the database column t_file_region_items.item_abstract
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    private String itemAbstract;

    /**
     * 创建人fid
     * This field corresponds to the database column t_file_region_items.create_fid
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    private String createFid;

    /**
     * 创建时间
     * This field corresponds to the database column t_file_region_items.create_date
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    private Date createDate;

    /**
     * 最后更新时间
     * This field corresponds to the database column t_file_region_items.last_modify_date
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    private Date lastModifyDate;

    /**
     * 是否删除 0：否，1：是
     * This field corresponds to the database column t_file_region_items.is_del
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    private Integer isDel;

    /**
     * 项目内容
     * This field corresponds to the database column t_file_region_items.item_content
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    private String itemContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_region_items.id
     *
     * @return the value of t_file_region_items.id
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_region_items.id
     *
     * @param id the value for t_file_region_items.id
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_region_items.fid
     *
     * @return the value of t_file_region_items.fid
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_region_items.fid
     *
     * @param fid the value for t_file_region_items.fid
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_region_items.hot_region_fid
     *
     * @return the value of t_file_region_items.hot_region_fid
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    public String getHotRegionFid() {
        return hotRegionFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_region_items.hot_region_fid
     *
     * @param hotRegionFid the value for t_file_region_items.hot_region_fid
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    public void setHotRegionFid(String hotRegionFid) {
        this.hotRegionFid = hotRegionFid == null ? null : hotRegionFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_region_items.item_name
     *
     * @return the value of t_file_region_items.item_name
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_region_items.item_name
     *
     * @param itemName the value for t_file_region_items.item_name
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_region_items.item_brief
     *
     * @return the value of t_file_region_items.item_brief
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    public String getItemBrief() {
        return itemBrief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_region_items.item_brief
     *
     * @param itemBrief the value for t_file_region_items.item_brief
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    public void setItemBrief(String itemBrief) {
        this.itemBrief = itemBrief == null ? null : itemBrief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_region_items.item_abstract
     *
     * @return the value of t_file_region_items.item_abstract
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    public String getItemAbstract() {
        return itemAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_region_items.item_abstract
     *
     * @param itemAbstract the value for t_file_region_items.item_abstract
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    public void setItemAbstract(String itemAbstract) {
        this.itemAbstract = itemAbstract == null ? null : itemAbstract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_region_items.create_fid
     *
     * @return the value of t_file_region_items.create_fid
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    public String getCreateFid() {
        return createFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_region_items.create_fid
     *
     * @param createFid the value for t_file_region_items.create_fid
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    public void setCreateFid(String createFid) {
        this.createFid = createFid == null ? null : createFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_region_items.create_date
     *
     * @return the value of t_file_region_items.create_date
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_region_items.create_date
     *
     * @param createDate the value for t_file_region_items.create_date
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_region_items.last_modify_date
     *
     * @return the value of t_file_region_items.last_modify_date
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_region_items.last_modify_date
     *
     * @param lastModifyDate the value for t_file_region_items.last_modify_date
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_region_items.is_del
     *
     * @return the value of t_file_region_items.is_del
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_region_items.is_del
     *
     * @param isDel the value for t_file_region_items.is_del
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_region_items.item_content
     *
     * @return the value of t_file_region_items.item_content
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    public String getItemContent() {
        return itemContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_region_items.item_content
     *
     * @param itemContent the value for t_file_region_items.item_content
     *
     * @mbggenerated Mon Nov 07 14:24:52 CST 2016
     */
    public void setItemContent(String itemContent) {
        this.itemContent = itemContent == null ? null : itemContent.trim();
    }
}