package com.ziroom.minsu.entity.sys;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

/**
 * 
 * <p>用户负责城市entity</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author bushujie
 * @since 1.0
 * @version 1.0
 */
public class CurrentuserCityEntity extends BaseEntity {
    /**
	 * 序列化fid
	 */
	private static final long serialVersionUID = -6753933181089718926L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_currentuser_city.id
     *
     * @mbggenerated Mon Oct 24 14:15:40 CST 2016
     */
    private Integer id;

    /**
     * 用户fid
     * This field corresponds to the database column t_currentuser_city.currentuser_fid
     *
     * @mbggenerated Mon Oct 24 14:15:40 CST 2016
     */
    private String currentuserFid;

    /**
     * 国家code
     * This field corresponds to the database column t_currentuser_city.nation_code
     *
     * @mbggenerated Mon Oct 24 14:15:40 CST 2016
     */
    private String nationCode;

    /**
     * 省code
     * This field corresponds to the database column t_currentuser_city.province_code
     *
     * @mbggenerated Mon Oct 24 14:15:40 CST 2016
     */
    private String provinceCode;

    /**
     * 城市code
     * This field corresponds to the database column t_currentuser_city.city_code
     *
     * @mbggenerated Mon Oct 24 14:15:40 CST 2016
     */
    private String cityCode;

    /**
     * 区域code
     * This field corresponds to the database column t_currentuser_city.area_code
     *
     * @mbggenerated Mon Oct 24 14:15:40 CST 2016
     */
    private String areaCode;

    /**
     * 创建时间
     * This field corresponds to the database column t_currentuser_city.create_date
     *
     * @mbggenerated Mon Oct 24 14:15:40 CST 2016
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_currentuser_city.id
     *
     * @return the value of t_currentuser_city.id
     *
     * @mbggenerated Mon Oct 24 14:15:40 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_currentuser_city.id
     *
     * @param id the value for t_currentuser_city.id
     *
     * @mbggenerated Mon Oct 24 14:15:40 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_currentuser_city.currentuser_fid
     *
     * @return the value of t_currentuser_city.currentuser_fid
     *
     * @mbggenerated Mon Oct 24 14:15:40 CST 2016
     */
    public String getCurrentuserFid() {
        return currentuserFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_currentuser_city.currentuser_fid
     *
     * @param currentuserFid the value for t_currentuser_city.currentuser_fid
     *
     * @mbggenerated Mon Oct 24 14:15:40 CST 2016
     */
    public void setCurrentuserFid(String currentuserFid) {
        this.currentuserFid = currentuserFid == null ? null : currentuserFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_currentuser_city.nation_code
     *
     * @return the value of t_currentuser_city.nation_code
     *
     * @mbggenerated Mon Oct 24 14:15:40 CST 2016
     */
    public String getNationCode() {
        return nationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_currentuser_city.nation_code
     *
     * @param nationCode the value for t_currentuser_city.nation_code
     *
     * @mbggenerated Mon Oct 24 14:15:40 CST 2016
     */
    public void setNationCode(String nationCode) {
        this.nationCode = nationCode == null ? null : nationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_currentuser_city.province_code
     *
     * @return the value of t_currentuser_city.province_code
     *
     * @mbggenerated Mon Oct 24 14:15:40 CST 2016
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_currentuser_city.province_code
     *
     * @param provinceCode the value for t_currentuser_city.province_code
     *
     * @mbggenerated Mon Oct 24 14:15:40 CST 2016
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_currentuser_city.city_code
     *
     * @return the value of t_currentuser_city.city_code
     *
     * @mbggenerated Mon Oct 24 14:15:40 CST 2016
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_currentuser_city.city_code
     *
     * @param cityCode the value for t_currentuser_city.city_code
     *
     * @mbggenerated Mon Oct 24 14:15:40 CST 2016
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_currentuser_city.area_code
     *
     * @return the value of t_currentuser_city.area_code
     *
     * @mbggenerated Mon Oct 24 14:15:40 CST 2016
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_currentuser_city.area_code
     *
     * @param areaCode the value for t_currentuser_city.area_code
     *
     * @mbggenerated Mon Oct 24 14:15:40 CST 2016
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_currentuser_city.create_date
     *
     * @return the value of t_currentuser_city.create_date
     *
     * @mbggenerated Mon Oct 24 14:15:40 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_currentuser_city.create_date
     *
     * @param createDate the value for t_currentuser_city.create_date
     *
     * @mbggenerated Mon Oct 24 14:15:40 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}