package com.ziroom.minsu.entity.sys;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;
/**
 * 
 * <p>系统实体类</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author bushujie
 * @since 1.0
 * @version 1.0
 */
public class SystemsEntity extends BaseEntity{
    /**
	 * 序列化id
	 */
	private static final long serialVersionUID = 5328614944394421822L;

	/**
     * 自增id
     * This field corresponds to the database column t_sys_systems.id
     *
     * @mbggenerated Thu Dec 01 14:21:44 CST 2016
     */
    private Integer id;

    /**
     * 逻辑fid
     * This field corresponds to the database column t_sys_systems.fid
     *
     * @mbggenerated Thu Dec 01 14:21:44 CST 2016
     */
    private String fid;

    /**
     * 系统code
     * This field corresponds to the database column t_sys_systems.sys_code
     *
     * @mbggenerated Thu Dec 01 14:21:44 CST 2016
     */
    private String sysCode;

    /**
     * 系统名称
     * This field corresponds to the database column t_sys_systems.sys_name
     *
     * @mbggenerated Thu Dec 01 14:21:44 CST 2016
     */
    private String sysName;

    /**
     * 系统访问地址
     * This field corresponds to the database column t_sys_systems.sys_url
     *
     * @mbggenerated Thu Dec 01 14:21:44 CST 2016
     */
    private String sysUrl;

    /**
     * 创建时间
     * This field corresponds to the database column t_sys_systems.create_date
     *
     * @mbggenerated Thu Dec 01 14:21:44 CST 2016
     */
    private Date createDate;

    /**
     * 最后修改时间
     * This field corresponds to the database column t_sys_systems.last_modify_date
     *
     * @mbggenerated Thu Dec 01 14:21:44 CST 2016
     */
    private Date lastModifyDate;

    /**
     * 是否删除 0：否，1：是
     * This field corresponds to the database column t_sys_systems.is_del
     *
     * @mbggenerated Thu Dec 01 14:21:44 CST 2016
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_systems.id
     *
     * @return the value of t_sys_systems.id
     *
     * @mbggenerated Thu Dec 01 14:21:44 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_systems.id
     *
     * @param id the value for t_sys_systems.id
     *
     * @mbggenerated Thu Dec 01 14:21:44 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_systems.fid
     *
     * @return the value of t_sys_systems.fid
     *
     * @mbggenerated Thu Dec 01 14:21:44 CST 2016
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_systems.fid
     *
     * @param fid the value for t_sys_systems.fid
     *
     * @mbggenerated Thu Dec 01 14:21:44 CST 2016
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_systems.sys_code
     *
     * @return the value of t_sys_systems.sys_code
     *
     * @mbggenerated Thu Dec 01 14:21:44 CST 2016
     */
    public String getSysCode() {
        return sysCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_systems.sys_code
     *
     * @param sysCode the value for t_sys_systems.sys_code
     *
     * @mbggenerated Thu Dec 01 14:21:44 CST 2016
     */
    public void setSysCode(String sysCode) {
        this.sysCode = sysCode == null ? null : sysCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_systems.sys_name
     *
     * @return the value of t_sys_systems.sys_name
     *
     * @mbggenerated Thu Dec 01 14:21:44 CST 2016
     */
    public String getSysName() {
        return sysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_systems.sys_name
     *
     * @param sysName the value for t_sys_systems.sys_name
     *
     * @mbggenerated Thu Dec 01 14:21:44 CST 2016
     */
    public void setSysName(String sysName) {
        this.sysName = sysName == null ? null : sysName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_systems.sys_url
     *
     * @return the value of t_sys_systems.sys_url
     *
     * @mbggenerated Thu Dec 01 14:21:44 CST 2016
     */
    public String getSysUrl() {
        return sysUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_systems.sys_url
     *
     * @param sysUrl the value for t_sys_systems.sys_url
     *
     * @mbggenerated Thu Dec 01 14:21:44 CST 2016
     */
    public void setSysUrl(String sysUrl) {
        this.sysUrl = sysUrl == null ? null : sysUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_systems.create_date
     *
     * @return the value of t_sys_systems.create_date
     *
     * @mbggenerated Thu Dec 01 14:21:44 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_systems.create_date
     *
     * @param createDate the value for t_sys_systems.create_date
     *
     * @mbggenerated Thu Dec 01 14:21:44 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_systems.last_modify_date
     *
     * @return the value of t_sys_systems.last_modify_date
     *
     * @mbggenerated Thu Dec 01 14:21:44 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_systems.last_modify_date
     *
     * @param lastModifyDate the value for t_sys_systems.last_modify_date
     *
     * @mbggenerated Thu Dec 01 14:21:44 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_systems.is_del
     *
     * @return the value of t_sys_systems.is_del
     *
     * @mbggenerated Thu Dec 01 14:21:44 CST 2016
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_systems.is_del
     *
     * @param isDel the value for t_sys_systems.is_del
     *
     * @mbggenerated Thu Dec 01 14:21:44 CST 2016
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}