
package com.zra.common.esp.signcheck;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "itrusUtilPortType", targetNamespace = "http://itrus.com/itrusUtil")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ItrusUtilPortType {


    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://itrus.com/itrusUtil")
    @RequestWrapper(localName = "verify", targetNamespace = "http://itrus.com/itrusUtil", className = "Verify")
    @ResponseWrapper(localName = "verifyResponse", targetNamespace = "http://itrus.com/itrusUtil", className = "VerifyResponse")
    public String verify(
        @WebParam(name = "in0", targetNamespace = "http://itrus.com/itrusUtil")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://itrus.com/itrusUtil")
    @RequestWrapper(localName = "signature", targetNamespace = "http://itrus.com/itrusUtil", className = "Signature")
    @ResponseWrapper(localName = "signatureResponse", targetNamespace = "http://itrus.com/itrusUtil", className = "SignatureResponse")
    public String signature(
        @WebParam(name = "in0", targetNamespace = "http://itrus.com/itrusUtil")
        String in0);

}
