
package com.zra.common.esp.signcheck;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "itrusUtil", targetNamespace = "http://itrus.com/itrusUtil", wsdlLocation = "http://esp.ziroom.com/DigitalSignature_ws/services/itrusUtil?wsdl")
public class ItrusUtil
    extends Service
{

    private final static URL ITRUSUTIL_WSDL_LOCATION;
    private final static WebServiceException ITRUSUTIL_EXCEPTION;
    private final static QName ITRUSUTIL_QNAME = new QName("http://itrus.com/itrusUtil", "itrusUtil");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://esp.ziroom.com/DigitalSignature_ws/services/itrusUtil?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ITRUSUTIL_WSDL_LOCATION = url;
        ITRUSUTIL_EXCEPTION = e;
    }

    public ItrusUtil() {
        super(__getWsdlLocation(), ITRUSUTIL_QNAME);
    }

    public ItrusUtil(WebServiceFeature... features) {
        super(__getWsdlLocation(), ITRUSUTIL_QNAME, features);
    }

    public ItrusUtil(URL wsdlLocation) {
        super(wsdlLocation, ITRUSUTIL_QNAME);
    }

    public ItrusUtil(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ITRUSUTIL_QNAME, features);
    }

    public ItrusUtil(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ItrusUtil(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ItrusUtilPortType
     */
    @WebEndpoint(name = "itrusUtilHttpPort")
    public ItrusUtilPortType getItrusUtilHttpPort() {
        return super.getPort(new QName("http://itrus.com/itrusUtil", "itrusUtilHttpPort"), ItrusUtilPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ItrusUtilPortType
     */
    @WebEndpoint(name = "itrusUtilHttpPort")
    public ItrusUtilPortType getItrusUtilHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://itrus.com/itrusUtil", "itrusUtilHttpPort"), ItrusUtilPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ITRUSUTIL_EXCEPTION!= null) {
            throw ITRUSUTIL_EXCEPTION;
        }
        return ITRUSUTIL_WSDL_LOCATION;
    }

}
