package com.ziroom.minsu.entity.evaluate;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

/**
 * 
 * <p>评价日志实体</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author yd
 * @since 1.0
 * @version 1.0
 */
public class EvaluateLogEntity  extends BaseEntity{
    /**
	 * 序列号
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_evaluate_log.id
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_evaluate_log.fid
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    private String fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_evaluate_log.eva_order_fid
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    private String evaOrderFid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_evaluate_log.from_status
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    private Integer fromStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_evaluate_log.to_status
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    private Integer toStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_evaluate_log.remark
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_evaluate_log.create_uid
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    private String createUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_evaluate_log.create_time
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_evaluate_log.is_del
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    private Integer isDel;
    
    public EvaluateLogEntity(){
    	this.setCreateTime(new Date());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate_log.id
     *
     * @return the value of t_evaluate_log.id
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate_log.id
     *
     * @param id the value for t_evaluate_log.id
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate_log.fid
     *
     * @return the value of t_evaluate_log.fid
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate_log.fid
     *
     * @param fid the value for t_evaluate_log.fid
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate_log.eva_order_fid
     *
     * @return the value of t_evaluate_log.eva_order_fid
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    public String getEvaOrderFid() {
        return evaOrderFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate_log.eva_order_fid
     *
     * @param evaOrderFid the value for t_evaluate_log.eva_order_fid
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    public void setEvaOrderFid(String evaOrderFid) {
        this.evaOrderFid = evaOrderFid == null ? null : evaOrderFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate_log.from_status
     *
     * @return the value of t_evaluate_log.from_status
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    public Integer getFromStatus() {
        return fromStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate_log.from_status
     *
     * @param fromStatus the value for t_evaluate_log.from_status
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    public void setFromStatus(Integer fromStatus) {
        this.fromStatus = fromStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate_log.to_status
     *
     * @return the value of t_evaluate_log.to_status
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    public Integer getToStatus() {
        return toStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate_log.to_status
     *
     * @param toStatus the value for t_evaluate_log.to_status
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    public void setToStatus(Integer toStatus) {
        this.toStatus = toStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate_log.remark
     *
     * @return the value of t_evaluate_log.remark
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate_log.remark
     *
     * @param remark the value for t_evaluate_log.remark
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate_log.create_uid
     *
     * @return the value of t_evaluate_log.create_uid
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    public String getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate_log.create_uid
     *
     * @param createUid the value for t_evaluate_log.create_uid
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    public void setCreateUid(String createUid) {
        this.createUid = createUid == null ? null : createUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate_log.create_time
     *
     * @return the value of t_evaluate_log.create_time
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate_log.create_time
     *
     * @param createTime the value for t_evaluate_log.create_time
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate_log.is_del
     *
     * @return the value of t_evaluate_log.is_del
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate_log.is_del
     *
     * @param isDel the value for t_evaluate_log.is_del
     *
     * @mbggenerated Thu Apr 07 20:15:04 CST 2016
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}