package com.ziroom.minsu.entity.evaluate;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

/**
 * 
 * <p>评价订单关系实体</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author yd
 * @since 1.0
 * @version 1.0
 */
public class EvaluateOrderEntity extends BaseEntity{
    /**
	 * 序列id
	 */
	private static final long serialVersionUID = -6803816634492817496L;

	/**
	 * 自增主键
	 */
    private Integer id;

    /**
     * 业务主键
     */
    private String fid;

    /**
     * 订单编号
     */
    private String orderSn;

    /**
     * 评价状态(1=待审核 2=已下线 3=已发布 4=已举报)
     */
    private Integer evaStatu;

    /**
     * 评价人uid(即创建人uid)
     */
    private String evaUserUid;

    /**
     * 被评人uid
     */
    private String ratedUserUid;

    /**
     * 评价人类型（房东=1 房客=2）
     */
    private Integer evaUserType;

    /**
     * 房源fid
     */
    private String houseFid;

    /**
     * 房间fid
     */
    private String roomFid;

    /**
     * 床fid
     */
    private String bedFid;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 最后修改时间
     */
    private Date lastModifyDate;
    
    /**
     * 出租类型 0：整租 1：合租 2：床位
     */
    private Integer rentWay;
    
    /**
     * 订单是否已评价标识 0=订单未修改成已评价，1=代表订单已修改成已评价
     */
    private Integer orderEvaFlag;

    public EvaluateOrderEntity(){
    	this.setCreateTime(new Date());
    	this.setLastModifyDate(new Date());
    	this.setEvaStatu(1);
    }
    
    public Integer getOrderEvaFlag() {
		return orderEvaFlag;
	}



	public void setOrderEvaFlag(Integer orderEvaFlag) {
		this.orderEvaFlag = orderEvaFlag;
	}



	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate_order.id
     *
     * @return the value of t_evaluate_order.id
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate_order.id
     *
     * @param id the value for t_evaluate_order.id
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate_order.fid
     *
     * @return the value of t_evaluate_order.fid
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate_order.fid
     *
     * @param fid the value for t_evaluate_order.fid
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate_order.order_sn
     *
     * @return the value of t_evaluate_order.order_sn
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate_order.order_sn
     *
     * @param orderSn the value for t_evaluate_order.order_sn
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate_order.eva_statu
     *
     * @return the value of t_evaluate_order.eva_statu
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public Integer getEvaStatu() {
        return evaStatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate_order.eva_statu
     *
     * @param evaStatu the value for t_evaluate_order.eva_statu
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setEvaStatu(Integer evaStatu) {
        this.evaStatu = evaStatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate_order.eva_user_uid
     *
     * @return the value of t_evaluate_order.eva_user_uid
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public String getEvaUserUid() {
        return evaUserUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate_order.eva_user_uid
     *
     * @param evaUserUid the value for t_evaluate_order.eva_user_uid
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setEvaUserUid(String evaUserUid) {
        this.evaUserUid = evaUserUid == null ? null : evaUserUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate_order.rated_user_uid
     *
     * @return the value of t_evaluate_order.rated_user_uid
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public String getRatedUserUid() {
        return ratedUserUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate_order.rated_user_uid
     *
     * @param ratedUserUid the value for t_evaluate_order.rated_user_uid
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setRatedUserUid(String ratedUserUid) {
        this.ratedUserUid = ratedUserUid == null ? null : ratedUserUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate_order.eva_user_type
     *
     * @return the value of t_evaluate_order.eva_user_type
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public Integer getEvaUserType() {
        return evaUserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate_order.eva_user_type
     *
     * @param evaUserType the value for t_evaluate_order.eva_user_type
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setEvaUserType(Integer evaUserType) {
        this.evaUserType = evaUserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate_order.house_fid
     *
     * @return the value of t_evaluate_order.house_fid
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public String getHouseFid() {
        return houseFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate_order.house_fid
     *
     * @param houseFid the value for t_evaluate_order.house_fid
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setHouseFid(String houseFid) {
        this.houseFid = houseFid == null ? null : houseFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate_order.room_fid
     *
     * @return the value of t_evaluate_order.room_fid
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public String getRoomFid() {
        return roomFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate_order.room_fid
     *
     * @param roomFid the value for t_evaluate_order.room_fid
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setRoomFid(String roomFid) {
        this.roomFid = roomFid == null ? null : roomFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate_order.bed_fid
     *
     * @return the value of t_evaluate_order.bed_fid
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public String getBedFid() {
        return bedFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate_order.bed_fid
     *
     * @param bedFid the value for t_evaluate_order.bed_fid
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setBedFid(String bedFid) {
        this.bedFid = bedFid == null ? null : bedFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate_order.create_time
     *
     * @return the value of t_evaluate_order.create_time
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate_order.create_time
     *
     * @param createTime the value for t_evaluate_order.create_time
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate_order.last_modify_date
     *
     * @return the value of t_evaluate_order.last_modify_date
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate_order.last_modify_date
     *
     * @param lastModifyDate the value for t_evaluate_order.last_modify_date
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

	public Integer getRentWay() {
		return rentWay;
	}

	public void setRentWay(Integer rentWay) {
		this.rentWay = rentWay;
	}
}