package com.ziroom.minsu.entity.evaluate;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

/**
 * 
 * <p>房东评价实体</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author yd
 * @since 1.0
 * @version 1.0
 */
public class LandlordEvaluateEntity extends BaseEntity{
    /**
	 * 序列id
	 */
	private static final long serialVersionUID = -1805109407266597459L;

	/**
	 * 自增主键
	 */
    private Integer id;

    /**
     * 业务主键
     */
    private String fid;

    /**
     * 订单评价fid
     */
    private String evaOrderFid;

    /**
     * 房东对房客的满意星级(1颗星 2颗星 3颗星 4颗星 5颗星 5是最满意 1是最不满意)
     */
    private Integer landlordSatisfied;

    /**
     * 评价内容
     */
    private String content;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 最后修改时间
     */
    private Date lastModifyDate;

    /**
     * 是否删除 0：否，1：是
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_landlord_evaluate.id
     *
     * @return the value of t_landlord_evaluate.id
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_landlord_evaluate.id
     *
     * @param id the value for t_landlord_evaluate.id
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_landlord_evaluate.fid
     *
     * @return the value of t_landlord_evaluate.fid
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_landlord_evaluate.fid
     *
     * @param fid the value for t_landlord_evaluate.fid
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_landlord_evaluate.eva_order_fid
     *
     * @return the value of t_landlord_evaluate.eva_order_fid
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public String getEvaOrderFid() {
        return evaOrderFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_landlord_evaluate.eva_order_fid
     *
     * @param evaOrderFid the value for t_landlord_evaluate.eva_order_fid
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setEvaOrderFid(String evaOrderFid) {
        this.evaOrderFid = evaOrderFid == null ? null : evaOrderFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_landlord_evaluate.landlord_satisfied
     *
     * @return the value of t_landlord_evaluate.landlord_satisfied
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public Integer getLandlordSatisfied() {
        return landlordSatisfied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_landlord_evaluate.landlord_satisfied
     *
     * @param landlordSatisfied the value for t_landlord_evaluate.landlord_satisfied
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setLandlordSatisfied(Integer landlordSatisfied) {
        this.landlordSatisfied = landlordSatisfied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_landlord_evaluate.content
     *
     * @return the value of t_landlord_evaluate.content
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_landlord_evaluate.content
     *
     * @param content the value for t_landlord_evaluate.content
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_landlord_evaluate.create_time
     *
     * @return the value of t_landlord_evaluate.create_time
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_landlord_evaluate.create_time
     *
     * @param createTime the value for t_landlord_evaluate.create_time
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_landlord_evaluate.last_modify_date
     *
     * @return the value of t_landlord_evaluate.last_modify_date
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_landlord_evaluate.last_modify_date
     *
     * @param lastModifyDate the value for t_landlord_evaluate.last_modify_date
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_landlord_evaluate.is_del
     *
     * @return the value of t_landlord_evaluate.is_del
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_landlord_evaluate.is_del
     *
     * @param isDel the value for t_landlord_evaluate.is_del
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}