package com.ziroom.minsu.entity.evaluate;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;
/**
 * 
 * <p>统计房源评价信息</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author yd
 * @since 1.0
 * @version 1.0
 */
public class StatsHouseEvaEntity extends BaseEntity{
    /**
	 * 序列id
	 */
	private static final long serialVersionUID = -52419130807325802L;

	/**
	 * 自增主键
	 * 
	 */
    private Integer id;

    /**
     * 业务编号
     */
    private String fid;

    /**
     * 房源fid
     */
    private String houseFid;

    /**
     * 房间fid
     */
    private String roomFid;

    /**
     * 床fid
     */
    private String bedFid;

    /**
     * 整洁卫生星级平均值
     */
    private Float houseCleanAva;

    /**
     * 描述相符星级平均值
     */
    private Float desMatchAva;

    /**
     * 安全程度星级平均值
     */
    private Float safeDegreeAva;

    /**
     * 交通位置星级平均值
     */
    private Float trafPosAva;

    /**
     * 性价比星级平均值
     */
    private Float costPerforAva;

    /**
     * 评价4星级平均值
     */
    private Float evaFourAvage;

    /**
     * 评价5星级平均值
     */
    private Float evaFiveAvage;

    /**
     * 出租类型 0：整租 1：合租 2：床
     */
    private Integer rentWay;

    /**
     * 房东的uid
     */
    private String landlordUid;

    /**
     * 整洁卫生总得分
     */
    private Integer houseCleanTal;

    /**
     * 描述相符总得分
     */
    private Integer desMathTal;

    /**
     * 安全程度总得分
     */
    private Integer safeDegreeTal;

    /**
     * 交通位置总得分
     */
    private Integer trafPosTal;

    /**
     * 性价比总得分
     */
    private Integer costPerforTal;

    /**
     * 评价4总得分
     */
    private Integer evaFourTal;

    /**
     * 评价5总得分
     */
    private Integer evaFiveTal;

    /**
     * 评论总数
     */
    private Integer evaTotal;

    /**
     * 最后修改时间 
     */
    private Date lastModifyDate;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_house_eva.id
     *
     * @return the value of t_stats_house_eva.id
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_house_eva.id
     *
     * @param id the value for t_stats_house_eva.id
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_house_eva.fid
     *
     * @return the value of t_stats_house_eva.fid
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_house_eva.fid
     *
     * @param fid the value for t_stats_house_eva.fid
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_house_eva.house_fid
     *
     * @return the value of t_stats_house_eva.house_fid
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public String getHouseFid() {
        return houseFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_house_eva.house_fid
     *
     * @param houseFid the value for t_stats_house_eva.house_fid
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setHouseFid(String houseFid) {
        this.houseFid = houseFid == null ? null : houseFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_house_eva.room_fid
     *
     * @return the value of t_stats_house_eva.room_fid
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public String getRoomFid() {
        return roomFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_house_eva.room_fid
     *
     * @param roomFid the value for t_stats_house_eva.room_fid
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setRoomFid(String roomFid) {
        this.roomFid = roomFid == null ? null : roomFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_house_eva.bed_fid
     *
     * @return the value of t_stats_house_eva.bed_fid
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public String getBedFid() {
        return bedFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_house_eva.bed_fid
     *
     * @param bedFid the value for t_stats_house_eva.bed_fid
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setBedFid(String bedFid) {
        this.bedFid = bedFid == null ? null : bedFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_house_eva.house_clean_ava
     *
     * @return the value of t_stats_house_eva.house_clean_ava
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public Float getHouseCleanAva() {
        return houseCleanAva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_house_eva.house_clean_ava
     *
     * @param houseCleanAva the value for t_stats_house_eva.house_clean_ava
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setHouseCleanAva(Float houseCleanAva) {
        this.houseCleanAva = houseCleanAva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_house_eva.des_match_ava
     *
     * @return the value of t_stats_house_eva.des_match_ava
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public Float getDesMatchAva() {
        return desMatchAva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_house_eva.des_match_ava
     *
     * @param desMatchAva the value for t_stats_house_eva.des_match_ava
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setDesMatchAva(Float desMatchAva) {
        this.desMatchAva = desMatchAva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_house_eva.safe_degree_ava
     *
     * @return the value of t_stats_house_eva.safe_degree_ava
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public Float getSafeDegreeAva() {
        return safeDegreeAva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_house_eva.safe_degree_ava
     *
     * @param safeDegreeAva the value for t_stats_house_eva.safe_degree_ava
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setSafeDegreeAva(Float safeDegreeAva) {
        this.safeDegreeAva = safeDegreeAva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_house_eva.traf_pos_ava
     *
     * @return the value of t_stats_house_eva.traf_pos_ava
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public Float getTrafPosAva() {
        return trafPosAva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_house_eva.traf_pos_ava
     *
     * @param trafPosAva the value for t_stats_house_eva.traf_pos_ava
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setTrafPosAva(Float trafPosAva) {
        this.trafPosAva = trafPosAva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_house_eva.cost_perfor_ava
     *
     * @return the value of t_stats_house_eva.cost_perfor_ava
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public Float getCostPerforAva() {
        return costPerforAva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_house_eva.cost_perfor_ava
     *
     * @param costPerforAva the value for t_stats_house_eva.cost_perfor_ava
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setCostPerforAva(Float costPerforAva) {
        this.costPerforAva = costPerforAva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_house_eva.eva_four_avage
     *
     * @return the value of t_stats_house_eva.eva_four_avage
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public Float getEvaFourAvage() {
        return evaFourAvage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_house_eva.eva_four_avage
     *
     * @param evaFourAvage the value for t_stats_house_eva.eva_four_avage
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setEvaFourAvage(Float evaFourAvage) {
        this.evaFourAvage = evaFourAvage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_house_eva.eva_five_avage
     *
     * @return the value of t_stats_house_eva.eva_five_avage
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public Float getEvaFiveAvage() {
        return evaFiveAvage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_house_eva.eva_five_avage
     *
     * @param evaFiveAvage the value for t_stats_house_eva.eva_five_avage
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setEvaFiveAvage(Float evaFiveAvage) {
        this.evaFiveAvage = evaFiveAvage;
    }

 

    public Integer getRentWay() {
		return rentWay;
	}

	public void setRentWay(Integer rentWay) {
		this.rentWay = rentWay;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_house_eva.landlord_uid
     *
     * @return the value of t_stats_house_eva.landlord_uid
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public String getLandlordUid() {
        return landlordUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_house_eva.landlord_uid
     *
     * @param landlordUid the value for t_stats_house_eva.landlord_uid
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setLandlordUid(String landlordUid) {
        this.landlordUid = landlordUid == null ? null : landlordUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_house_eva.house_clean_tal
     *
     * @return the value of t_stats_house_eva.house_clean_tal
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public Integer getHouseCleanTal() {
        return houseCleanTal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_house_eva.house_clean_tal
     *
     * @param houseCleanTal the value for t_stats_house_eva.house_clean_tal
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setHouseCleanTal(Integer houseCleanTal) {
        this.houseCleanTal = houseCleanTal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_house_eva.des_math_tal
     *
     * @return the value of t_stats_house_eva.des_math_tal
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public Integer getDesMathTal() {
        return desMathTal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_house_eva.des_math_tal
     *
     * @param desMathTal the value for t_stats_house_eva.des_math_tal
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setDesMathTal(Integer desMathTal) {
        this.desMathTal = desMathTal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_house_eva.safe_degree_tal
     *
     * @return the value of t_stats_house_eva.safe_degree_tal
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public Integer getSafeDegreeTal() {
        return safeDegreeTal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_house_eva.safe_degree_tal
     *
     * @param safeDegreeTal the value for t_stats_house_eva.safe_degree_tal
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setSafeDegreeTal(Integer safeDegreeTal) {
        this.safeDegreeTal = safeDegreeTal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_house_eva.traf_pos_tal
     *
     * @return the value of t_stats_house_eva.traf_pos_tal
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public Integer getTrafPosTal() {
        return trafPosTal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_house_eva.traf_pos_tal
     *
     * @param trafPosTal the value for t_stats_house_eva.traf_pos_tal
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setTrafPosTal(Integer trafPosTal) {
        this.trafPosTal = trafPosTal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_house_eva.cost_perfor_tal
     *
     * @return the value of t_stats_house_eva.cost_perfor_tal
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public Integer getCostPerforTal() {
        return costPerforTal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_house_eva.cost_perfor_tal
     *
     * @param costPerforTal the value for t_stats_house_eva.cost_perfor_tal
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setCostPerforTal(Integer costPerforTal) {
        this.costPerforTal = costPerforTal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_house_eva.eva_four_tal
     *
     * @return the value of t_stats_house_eva.eva_four_tal
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public Integer getEvaFourTal() {
        return evaFourTal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_house_eva.eva_four_tal
     *
     * @param evaFourTal the value for t_stats_house_eva.eva_four_tal
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setEvaFourTal(Integer evaFourTal) {
        this.evaFourTal = evaFourTal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_house_eva.eva_five_tal
     *
     * @return the value of t_stats_house_eva.eva_five_tal
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public Integer getEvaFiveTal() {
        return evaFiveTal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_house_eva.eva_five_tal
     *
     * @param evaFiveTal the value for t_stats_house_eva.eva_five_tal
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setEvaFiveTal(Integer evaFiveTal) {
        this.evaFiveTal = evaFiveTal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_house_eva.eva_total
     *
     * @return the value of t_stats_house_eva.eva_total
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public Integer getEvaTotal() {
        return evaTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_house_eva.eva_total
     *
     * @param evaTotal the value for t_stats_house_eva.eva_total
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setEvaTotal(Integer evaTotal) {
        this.evaTotal = evaTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_house_eva.last_modify_date
     *
     * @return the value of t_stats_house_eva.last_modify_date
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_house_eva.last_modify_date
     *
     * @param lastModifyDate the value for t_stats_house_eva.last_modify_date
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_house_eva.create_time
     *
     * @return the value of t_stats_house_eva.create_time
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_house_eva.create_time
     *
     * @param createTime the value for t_stats_house_eva.create_time
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}