package com.ziroom.minsu.entity.evaluate;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

/**
 * 
 * <p>统计房东对房客满意度实体</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author yd
 * @since 1.0
 * @version 1.0
 */
public class StatsTenantEvaEntity extends BaseEntity{
    /**
	 * 序列id
	 */
	private static final long serialVersionUID = 8783243527254211075L;

	/**
	 * 自增主键
	 */
    private Integer id;

    /**
     * 业务编号
     */
    private String fid;

    /**
     * 房东对房客的满意程度平均值
     */
    private Float landSatisfAva;

    /**
     * 房客的uid
     */
    private String tenantUid;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 最后修改时间
     */
    private Date lastModifyDate;

    /**
     * 房东对房客的满意程度总得分
     */
    private Integer landSatisfTal;

    /**
     * 评论总数
     */
    private Integer evaTotal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_tenant_eva.id
     *
     * @return the value of t_stats_tenant_eva.id
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_tenant_eva.id
     *
     * @param id the value for t_stats_tenant_eva.id
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_tenant_eva.fid
     *
     * @return the value of t_stats_tenant_eva.fid
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_tenant_eva.fid
     *
     * @param fid the value for t_stats_tenant_eva.fid
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_tenant_eva.land_satisf_ava
     *
     * @return the value of t_stats_tenant_eva.land_satisf_ava
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public Float getLandSatisfAva() {
        return landSatisfAva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_tenant_eva.land_satisf_ava
     *
     * @param landSatisfAva the value for t_stats_tenant_eva.land_satisf_ava
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setLandSatisfAva(Float landSatisfAva) {
        this.landSatisfAva = landSatisfAva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_tenant_eva.tenant_uid
     *
     * @return the value of t_stats_tenant_eva.tenant_uid
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public String getTenantUid() {
        return tenantUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_tenant_eva.tenant_uid
     *
     * @param tenantUid the value for t_stats_tenant_eva.tenant_uid
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setTenantUid(String tenantUid) {
        this.tenantUid = tenantUid == null ? null : tenantUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_tenant_eva.create_time
     *
     * @return the value of t_stats_tenant_eva.create_time
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_tenant_eva.create_time
     *
     * @param createTime the value for t_stats_tenant_eva.create_time
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_tenant_eva.last_modify_date
     *
     * @return the value of t_stats_tenant_eva.last_modify_date
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_tenant_eva.last_modify_date
     *
     * @param lastModifyDate the value for t_stats_tenant_eva.last_modify_date
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_tenant_eva.land_satisf_tal
     *
     * @return the value of t_stats_tenant_eva.land_satisf_tal
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public Integer getLandSatisfTal() {
        return landSatisfTal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_tenant_eva.land_satisf_tal
     *
     * @param landSatisfTal the value for t_stats_tenant_eva.land_satisf_tal
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setLandSatisfTal(Integer landSatisfTal) {
        this.landSatisfTal = landSatisfTal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stats_tenant_eva.eva_total
     *
     * @return the value of t_stats_tenant_eva.eva_total
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public Integer getEvaTotal() {
        return evaTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stats_tenant_eva.eva_total
     *
     * @param evaTotal the value for t_stats_tenant_eva.eva_total
     *
     * @mbggenerated Fri Apr 08 17:02:28 CST 2016
     */
    public void setEvaTotal(Integer evaTotal) {
        this.evaTotal = evaTotal;
    }
}