package com.ziroom.minsu.entity.evaluate;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

/**
 * 
 * <p>房客评价</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author yd
 * @since 1.0
 * @version 1.0
 */
public class TenantEvaluateEntity extends BaseEntity{
    /**
	 * 序列id
	 */
	private static final long serialVersionUID = -7376614263833218626L;

	/**
	 * 自增主键
	 */
    private Integer id;

    /**
     * 业务编号
     */
    private String fid;

    /**
     * 评价订单fid
     */
    private String evaOrderFid;

    /**
     * 评价内容
     */
    private String content;

   /**
    * 整洁卫生星级（1颗星 2颗星 3颗星 4颗星 5颗星 5为最满意）
    */
    private Integer houseClean;

    /**
     * 描述相符星级（1颗星 2颗星 3颗星 4颗星 5颗星 5为最满意
     */
    private Integer descriptionMatch;

    /**
     * 安全程度（1颗星 2颗星 3颗星 4颗星 5颗星 5为最满意）
     */
    private Integer safetyDegree;

    /**
     * 交通位置星级(1颗星 2颗星 3颗星 4颗星 5颗星 5为最满意）
     */
    private Integer trafficPosition;

   /**
    * 性价比（1颗星 2颗星 3颗星 4颗星 5颗星 5为最满意）
    */
    private Integer costPerformance;

    /**
     * 评价4（1颗星 2颗星 3颗星 4颗星 5颗星 5为最满意）
     */
    private Integer evaFour;

    /***
     * 评价5（1颗星 2颗星 3颗星 4颗星 5颗星 5为最满意）
     */
    private Integer evaFive;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 最后修改时间
     */
    private Date lastModifyDate;

    /**
     * 是否删除：0=不删除 1=删除
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tenant_evaluate.id
     *
     * @return the value of t_tenant_evaluate.id
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tenant_evaluate.id
     *
     * @param id the value for t_tenant_evaluate.id
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tenant_evaluate.fid
     *
     * @return the value of t_tenant_evaluate.fid
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tenant_evaluate.fid
     *
     * @param fid the value for t_tenant_evaluate.fid
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tenant_evaluate.eva_order_fid
     *
     * @return the value of t_tenant_evaluate.eva_order_fid
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public String getEvaOrderFid() {
        return evaOrderFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tenant_evaluate.eva_order_fid
     *
     * @param evaOrderFid the value for t_tenant_evaluate.eva_order_fid
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setEvaOrderFid(String evaOrderFid) {
        this.evaOrderFid = evaOrderFid == null ? null : evaOrderFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tenant_evaluate.content
     *
     * @return the value of t_tenant_evaluate.content
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tenant_evaluate.content
     *
     * @param content the value for t_tenant_evaluate.content
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tenant_evaluate.house_clean
     *
     * @return the value of t_tenant_evaluate.house_clean
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public Integer getHouseClean() {
        return houseClean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tenant_evaluate.house_clean
     *
     * @param houseClean the value for t_tenant_evaluate.house_clean
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setHouseClean(Integer houseClean) {
        this.houseClean = houseClean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tenant_evaluate.description_match
     *
     * @return the value of t_tenant_evaluate.description_match
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public Integer getDescriptionMatch() {
        return descriptionMatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tenant_evaluate.description_match
     *
     * @param descriptionMatch the value for t_tenant_evaluate.description_match
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setDescriptionMatch(Integer descriptionMatch) {
        this.descriptionMatch = descriptionMatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tenant_evaluate.safety_degree
     *
     * @return the value of t_tenant_evaluate.safety_degree
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public Integer getSafetyDegree() {
        return safetyDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tenant_evaluate.safety_degree
     *
     * @param safetyDegree the value for t_tenant_evaluate.safety_degree
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setSafetyDegree(Integer safetyDegree) {
        this.safetyDegree = safetyDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tenant_evaluate.traffic_position
     *
     * @return the value of t_tenant_evaluate.traffic_position
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public Integer getTrafficPosition() {
        return trafficPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tenant_evaluate.traffic_position
     *
     * @param trafficPosition the value for t_tenant_evaluate.traffic_position
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setTrafficPosition(Integer trafficPosition) {
        this.trafficPosition = trafficPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tenant_evaluate.cost_performance
     *
     * @return the value of t_tenant_evaluate.cost_performance
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public Integer getCostPerformance() {
        return costPerformance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tenant_evaluate.cost_performance
     *
     * @param costPerformance the value for t_tenant_evaluate.cost_performance
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setCostPerformance(Integer costPerformance) {
        this.costPerformance = costPerformance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tenant_evaluate.eva_four
     *
     * @return the value of t_tenant_evaluate.eva_four
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public Integer getEvaFour() {
        return evaFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tenant_evaluate.eva_four
     *
     * @param evaFour the value for t_tenant_evaluate.eva_four
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setEvaFour(Integer evaFour) {
        this.evaFour = evaFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tenant_evaluate.eva_five
     *
     * @return the value of t_tenant_evaluate.eva_five
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public Integer getEvaFive() {
        return evaFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tenant_evaluate.eva_five
     *
     * @param evaFive the value for t_tenant_evaluate.eva_five
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setEvaFive(Integer evaFive) {
        this.evaFive = evaFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tenant_evaluate.create_time
     *
     * @return the value of t_tenant_evaluate.create_time
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tenant_evaluate.create_time
     *
     * @param createTime the value for t_tenant_evaluate.create_time
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tenant_evaluate.last_modify_date
     *
     * @return the value of t_tenant_evaluate.last_modify_date
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tenant_evaluate.last_modify_date
     *
     * @param lastModifyDate the value for t_tenant_evaluate.last_modify_date
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tenant_evaluate.is_del
     *
     * @return the value of t_tenant_evaluate.is_del
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tenant_evaluate.is_del
     *
     * @param isDel the value for t_tenant_evaluate.is_del
     *
     * @mbggenerated Thu Apr 07 11:23:01 CST 2016
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}