package com.ziroom.minsu.entity.conf;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

/**
 * 
 * <p>序列id</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author yd
 * @since 1.0
 * @version 1.0
 */
public class GuardAreaLogEntity extends BaseEntity{
    /**
	 * 序列id
	 */
	private static final long serialVersionUID = -1348128964300361086L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_guard_area_log.id
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_guard_area_log.fid
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    private String fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_guard_area_log.gurad_area_fid
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    private String guradAreaFid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_guard_area_log.old_nation_code
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    private String oldNationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_guard_area_log.old_province_code
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    private String oldProvinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_guard_area_log.old_city_code
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    private String oldCityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_guard_area_log.old_area_code
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    private String oldAreaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_guard_area_log.guard_code
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    private String guardCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_guard_area_log.guard_name
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    private String guardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_guard_area_log.create_fid
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    private String createFid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_guard_area_log.create_date
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_guard_area_log.id
     *
     * @return the value of t_guard_area_log.id
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_guard_area_log.id
     *
     * @param id the value for t_guard_area_log.id
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_guard_area_log.fid
     *
     * @return the value of t_guard_area_log.fid
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_guard_area_log.fid
     *
     * @param fid the value for t_guard_area_log.fid
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_guard_area_log.gurad_area_fid
     *
     * @return the value of t_guard_area_log.gurad_area_fid
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    public String getGuradAreaFid() {
        return guradAreaFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_guard_area_log.gurad_area_fid
     *
     * @param guradAreaFid the value for t_guard_area_log.gurad_area_fid
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    public void setGuradAreaFid(String guradAreaFid) {
        this.guradAreaFid = guradAreaFid == null ? null : guradAreaFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_guard_area_log.old_nation_code
     *
     * @return the value of t_guard_area_log.old_nation_code
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    public String getOldNationCode() {
        return oldNationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_guard_area_log.old_nation_code
     *
     * @param oldNationCode the value for t_guard_area_log.old_nation_code
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    public void setOldNationCode(String oldNationCode) {
        this.oldNationCode = oldNationCode == null ? null : oldNationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_guard_area_log.old_province_code
     *
     * @return the value of t_guard_area_log.old_province_code
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    public String getOldProvinceCode() {
        return oldProvinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_guard_area_log.old_province_code
     *
     * @param oldProvinceCode the value for t_guard_area_log.old_province_code
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    public void setOldProvinceCode(String oldProvinceCode) {
        this.oldProvinceCode = oldProvinceCode == null ? null : oldProvinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_guard_area_log.old_city_code
     *
     * @return the value of t_guard_area_log.old_city_code
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    public String getOldCityCode() {
        return oldCityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_guard_area_log.old_city_code
     *
     * @param oldCityCode the value for t_guard_area_log.old_city_code
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    public void setOldCityCode(String oldCityCode) {
        this.oldCityCode = oldCityCode == null ? null : oldCityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_guard_area_log.old_area_code
     *
     * @return the value of t_guard_area_log.old_area_code
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    public String getOldAreaCode() {
        return oldAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_guard_area_log.old_area_code
     *
     * @param oldAreaCode the value for t_guard_area_log.old_area_code
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    public void setOldAreaCode(String oldAreaCode) {
        this.oldAreaCode = oldAreaCode == null ? null : oldAreaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_guard_area_log.guard_code
     *
     * @return the value of t_guard_area_log.guard_code
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    public String getGuardCode() {
        return guardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_guard_area_log.guard_code
     *
     * @param guardCode the value for t_guard_area_log.guard_code
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    public void setGuardCode(String guardCode) {
        this.guardCode = guardCode == null ? null : guardCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_guard_area_log.guard_name
     *
     * @return the value of t_guard_area_log.guard_name
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    public String getGuardName() {
        return guardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_guard_area_log.guard_name
     *
     * @param guardName the value for t_guard_area_log.guard_name
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    public void setGuardName(String guardName) {
        this.guardName = guardName == null ? null : guardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_guard_area_log.create_fid
     *
     * @return the value of t_guard_area_log.create_fid
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    public String getCreateFid() {
        return createFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_guard_area_log.create_fid
     *
     * @param createFid the value for t_guard_area_log.create_fid
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    public void setCreateFid(String createFid) {
        this.createFid = createFid == null ? null : createFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_guard_area_log.create_date
     *
     * @return the value of t_guard_area_log.create_date
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_guard_area_log.create_date
     *
     * @param createDate the value for t_guard_area_log.create_date
     *
     * @mbggenerated Tue Jul 05 14:51:00 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}