package com.ziroom.minsu.entity.conf;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;
import com.asura.framework.base.util.UUIDGenerator;

public class SmsTemplateEntity  extends BaseEntity{
    /**
	 * 序列id
	 */
	private static final long serialVersionUID = 3628011147754917308L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_template.id
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_template.fid
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    private String fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_template.sms_code
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    private String smsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_template.sms_name
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    private String smsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_template.sms_comment
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    private String smsComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_template.sms_enabled
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    private Integer smsEnabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_template.create_fid
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    private String createFid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_template.create_time
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_template.sms_type
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    private Integer smsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_template.last_modify_date
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    private Date lastModifyDate;
    
    public SmsTemplateEntity(){
    	this.setFid(UUIDGenerator.hexUUID());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_template.id
     *
     * @return the value of t_sms_template.id
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_template.id
     *
     * @param id the value for t_sms_template.id
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_template.fid
     *
     * @return the value of t_sms_template.fid
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_template.fid
     *
     * @param fid the value for t_sms_template.fid
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_template.sms_code
     *
     * @return the value of t_sms_template.sms_code
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    public String getSmsCode() {
        return smsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_template.sms_code
     *
     * @param smsCode the value for t_sms_template.sms_code
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    public void setSmsCode(String smsCode) {
        this.smsCode = smsCode == null ? null : smsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_template.sms_name
     *
     * @return the value of t_sms_template.sms_name
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    public String getSmsName() {
        return smsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_template.sms_name
     *
     * @param smsName the value for t_sms_template.sms_name
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    public void setSmsName(String smsName) {
        this.smsName = smsName == null ? null : smsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_template.sms_comment
     *
     * @return the value of t_sms_template.sms_comment
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    public String getSmsComment() {
        return smsComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_template.sms_comment
     *
     * @param smsComment the value for t_sms_template.sms_comment
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    public void setSmsComment(String smsComment) {
        this.smsComment = smsComment == null ? null : smsComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_template.sms_enabled
     *
     * @return the value of t_sms_template.sms_enabled
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    public Integer getSmsEnabled() {
        return smsEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_template.sms_enabled
     *
     * @param smsEnabled the value for t_sms_template.sms_enabled
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    public void setSmsEnabled(Integer smsEnabled) {
        this.smsEnabled = smsEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_template.create_fid
     *
     * @return the value of t_sms_template.create_fid
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    public String getCreateFid() {
        return createFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_template.create_fid
     *
     * @param createFid the value for t_sms_template.create_fid
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    public void setCreateFid(String createFid) {
        this.createFid = createFid == null ? null : createFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_template.create_time
     *
     * @return the value of t_sms_template.create_time
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_template.create_time
     *
     * @param createTime the value for t_sms_template.create_time
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_template.sms_type
     *
     * @return the value of t_sms_template.sms_type
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    public Integer getSmsType() {
        return smsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_template.sms_type
     *
     * @param smsType the value for t_sms_template.sms_type
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    public void setSmsType(Integer smsType) {
        this.smsType = smsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_template.last_modify_date
     *
     * @return the value of t_sms_template.last_modify_date
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_template.last_modify_date
     *
     * @param lastModifyDate the value for t_sms_template.last_modify_date
     *
     * @mbggenerated Sat Apr 02 17:40:15 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }
}