package com.zra.zmconfig.dao;

import com.zra.zmconfig.entity.CfShortUrl;

public interface CfShortUrlMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_short_url
     *
     * @mbggenerated Thu Aug 11 17:18:27 CST 2016
     */
    int insert(CfShortUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_short_url
     *
     * @mbggenerated Thu Aug 11 17:18:27 CST 2016
     */
    CfShortUrl selectByPrimaryKey(String suid);

}