package com.zra.cms.dao;

import com.zra.cms.entity.CmsProject;

public interface CmsProjectMapper {
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_project
     *
     * @mbggenerated Wed Mar 01 15:05:06 CST 2017
     */
    CmsProject selectByProjectId(String projectId);

}