package com.ziroom.minsu.entity.base;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

/**
 * 
 * <p>国家或地区电话码</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author bushujie
 * @since 1.0
 * @version 1.0
 */
public class NationCodeEntity extends BaseEntity{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1018657394657719317L;

	/**
     * 自增id
     * This field corresponds to the database column t_nation_code.id
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    private Integer id;

    /**
     * 逻辑fid
     * This field corresponds to the database column t_nation_code.fid
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    private String fid;

    /**
     * 国家code
     * This field corresponds to the database column t_nation_code.nation_code
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    private String nationCode;

    /**
     * 省code
     * This field corresponds to the database column t_nation_code.province_code
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    private String provinceCode;

    /**
     * 城市code
     * This field corresponds to the database column t_nation_code.city_code
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    private String cityCode;

    /**
     * 国家或地区名称
     * This field corresponds to the database column t_nation_code.nation_name
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    private String nationName;
    
    /**
     * 国家码
     */
    private String countryCode;

	/**
     * 创建时间
     * This field corresponds to the database column t_nation_code.create_date
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    private Date createDate;

    /**
     * 最后更新时间
     * This field corresponds to the database column t_nation_code.last_modify_date
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    private Date lastModifyDate;

    /**
     * 创建人fid
     * This field corresponds to the database column t_nation_code.create_fid
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    private String createFid;

    /**
     * 是否删除 0：否，1：是
     * This field corresponds to the database column t_nation_code.is_del
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nation_code.id
     *
     * @return the value of t_nation_code.id
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nation_code.id
     *
     * @param id the value for t_nation_code.id
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nation_code.fid
     *
     * @return the value of t_nation_code.fid
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nation_code.fid
     *
     * @param fid the value for t_nation_code.fid
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nation_code.nation_code
     *
     * @return the value of t_nation_code.nation_code
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    public String getNationCode() {
        return nationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nation_code.nation_code
     *
     * @param nationCode the value for t_nation_code.nation_code
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    public void setNationCode(String nationCode) {
        this.nationCode = nationCode == null ? null : nationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nation_code.province_code
     *
     * @return the value of t_nation_code.province_code
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nation_code.province_code
     *
     * @param provinceCode the value for t_nation_code.province_code
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nation_code.city_code
     *
     * @return the value of t_nation_code.city_code
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nation_code.city_code
     *
     * @param cityCode the value for t_nation_code.city_code
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nation_code.nation_name
     *
     * @return the value of t_nation_code.nation_name
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    public String getNationName() {
        return nationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nation_code.nation_name
     *
     * @param nationName the value for t_nation_code.nation_name
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    public void setNationName(String nationName) {
        this.nationName = nationName == null ? null : nationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nation_code.create_date
     *
     * @return the value of t_nation_code.create_date
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nation_code.create_date
     *
     * @param createDate the value for t_nation_code.create_date
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nation_code.last_modify_date
     *
     * @return the value of t_nation_code.last_modify_date
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nation_code.last_modify_date
     *
     * @param lastModifyDate the value for t_nation_code.last_modify_date
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nation_code.create_fid
     *
     * @return the value of t_nation_code.create_fid
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    public String getCreateFid() {
        return createFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nation_code.create_fid
     *
     * @param createFid the value for t_nation_code.create_fid
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    public void setCreateFid(String createFid) {
        this.createFid = createFid == null ? null : createFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nation_code.is_del
     *
     * @return the value of t_nation_code.is_del
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nation_code.is_del
     *
     * @param isDel the value for t_nation_code.is_del
     *
     * @mbggenerated Tue Apr 11 11:21:26 CST 2017
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
    
    /**
	 * @return the countryCode
	 */
	public String getCountryCode() {
		return countryCode;
	}

	/**
	 * @param countryCode the countryCode to set
	 */
	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}
}