package com.ziroom.minsu.entity.message;

import com.asura.framework.base.entity.BaseEntity;

import java.util.Date;

/**
 * 
 * <p>留言基本信息实体</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author yd
 * @since 1.0
 * @version 1.0
 */
public class MsgBaseEntity extends BaseEntity{
	/**
	 * 序列id
	 */
	private static final long serialVersionUID = -2528239202171987861L;

	/**
	 * 编号
	 */
	private Integer id;

	/**
	 * 业务编号
	 */
	private String fid;

	/**
	 * 消息体（即：消息内容）
	 */
	private String msgContent;

	/**
	 * 消息发送人类型（1=房东 2=房客）
	 */
	private Integer msgSenderType;

	/**
	 * 该消息是否是系统发送（0=否 1=是）add @Author:lusp @Date:2017/9/5
	 */
	private Integer isSystemSend;

	/**
	 * 单条记录是否删除 默认0(0：不删除 1：删除)
	 */
	private Integer isDel;

	/**
	 * 房源留言关联表fid
	 */
	private String msgHouseFid;

	/**
	 * 是否已读 默认0（0：已读 1：未读）
	 */
	private Integer isRead;

	/**
	 * 是否首次咨询 1=是 0=否
	 */
	private Integer houseCard;

	/**
	 * 创建时间
	 */
	private Date createTime;

	/**
	 * 房源fid或房间fid或床位fid
	 */
	private String houseFid;

	/**
	 * 出租类型 0：整租，1：合租，2：床位
	 */
	private Integer rentWay;


	/**
	 * 房东的回复时长:按房源维度统计
	 */
	private Long replayTimeHouse;

	/**
	 * 房东的回复时长:按房东维度统计
	 */
	private Long replayTimeLanlord;

	/**
	 * 消息体（即：消息内容 不包含扩展消息)
	 */
	private String msgRealContent;

	/**
	 * 环信消息的发送时间
	 */
	private Date msgSendTime;

	/**
	 * 上传图片消息地址，在上传图片成功后会返回UUID 或 上传语音远程地址，在上传语音后会返回UUID
	 */
	private String url;

	
	/**
	 * secret在上传图片后会返回，只有含有secret才能够下载此图片 或 secret在上传文件后会返回
	 */
	private String secret;
	
	/**
	 * 语音名称 或 图片名称
	 */
	private String filename;
	
	/**
	 * 图片附件大小 或 语音附件大小（单位：字节）
	 */
	private Integer fileLength;
	
	/**
	 * 环信消息类型txt: 文本消息；img: 图片；loc: 位置；audio: 语音
	 */
	private String type;
	
	/**
	 * 图片尺寸
	 */
	private String size;
	
	
	/**
	 * @return the size
	 */
	public String getSize() {
		return size;
	}

	/**
	 * @param size the size to set
	 */
	public void setSize(String size) {
		this.size = size;
	}

	/**
	 * @return the url
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * @param url the url to set
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * @return the secret
	 */
	public String getSecret() {
		return secret;
	}

	/**
	 * @param secret the secret to set
	 */
	public void setSecret(String secret) {
		this.secret = secret;
	}

	/**
	 * @return the filename
	 */
	public String getFilename() {
		return filename;
	}

	/**
	 * @param filename the filename to set
	 */
	public void setFilename(String filename) {
		this.filename = filename;
	}

	/**
	 * @return the fileLength
	 */
	public Integer getFileLength() {
		return fileLength;
	}

	/**
	 * @param fileLength the fileLength to set
	 */
	public void setFileLength(Integer fileLength) {
		this.fileLength = fileLength;
	}

	/**
	 * @return the type
	 */
	public String getType() {
		return type;
	}

	/**
	 * @param type the type to set
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * @return the msgSendTime
	 */
	public Date getMsgSendTime() {
		return msgSendTime;
	}

	/**
	 * @param msgSendTime the msgSendTime to set
	 */
	public void setMsgSendTime(Date msgSendTime) {
		this.msgSendTime = msgSendTime;
	}


	/**
	 * @return the msgRealContent
	 */
	public String getMsgRealContent() {
		return msgRealContent;
	}

	/**
	 * @param msgRealContent the msgRealContent to set
	 */
	public void setMsgRealContent(String msgRealContent) {
		this.msgRealContent = msgRealContent;
	}

	/**
	 * @return the replayTimeHouse
	 */
	public Long getReplayTimeHouse() {
		return replayTimeHouse;
	}

	/**
	 * @param replayTimeHouse the replayTimeHouse to set
	 */
	public void setReplayTimeHouse(Long replayTimeHouse) {
		this.replayTimeHouse = replayTimeHouse;
	}

	/**
	 * @return the replayTimeLanlord
	 */
	public Long getReplayTimeLanlord() {
		return replayTimeLanlord;
	}

	/**
	 * @param replayTimeLanlord the replayTimeLanlord to set
	 */
	public void setReplayTimeLanlord(Long replayTimeLanlord) {
		this.replayTimeLanlord = replayTimeLanlord;
	}

	/**
	 * @return the houseFid
	 */
	public String getHouseFid() {
		return houseFid;
	}

	/**
	 * @param houseFid the houseFid to set
	 */
	public void setHouseFid(String houseFid) {
		this.houseFid = houseFid;
	}

	/**
	 * @return the rentWay
	 */
	public Integer getRentWay() {
		return rentWay;
	}

	/**
	 * @param rentWay the rentWay to set
	 */
	public void setRentWay(Integer rentWay) {
		this.rentWay = rentWay;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_msg_base.id
	 *
	 * @return the value of t_msg_base.id
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_msg_base.id
	 *
	 * @param id the value for t_msg_base.id
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_msg_base.fid
	 *
	 * @return the value of t_msg_base.fid
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public String getFid() {
		return fid;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_msg_base.fid
	 *
	 * @param fid the value for t_msg_base.fid
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public void setFid(String fid) {
		this.fid = fid == null ? null : fid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_msg_base.msg_content
	 *
	 * @return the value of t_msg_base.msg_content
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public String getMsgContent() {
		return msgContent;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_msg_base.msg_content
	 *
	 * @param msgContent the value for t_msg_base.msg_content
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public void setMsgContent(String msgContent) {
		this.msgContent = msgContent == null ? null : msgContent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_msg_base.msg_sender_type
	 *
	 * @return the value of t_msg_base.msg_sender_type
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public Integer getMsgSenderType() {
		return msgSenderType;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_msg_base.msg_sender_type
	 *
	 * @param msgSenderType the value for t_msg_base.msg_sender_type
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public void setMsgSenderType(Integer msgSenderType) {
		this.msgSenderType = msgSenderType;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_msg_base.is_del
	 *
	 * @return the value of t_msg_base.is_del
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public Integer getIsDel() {
		return isDel;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_msg_base.is_del
	 *
	 * @param isDel the value for t_msg_base.is_del
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public void setIsDel(Integer isDel) {
		this.isDel = isDel;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_msg_base.msg_house_fid
	 *
	 * @return the value of t_msg_base.msg_house_fid
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public String getMsgHouseFid() {
		return msgHouseFid;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_msg_base.msg_house_fid
	 *
	 * @param msgHouseFid the value for t_msg_base.msg_house_fid
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public void setMsgHouseFid(String msgHouseFid) {
		this.msgHouseFid = msgHouseFid == null ? null : msgHouseFid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_msg_base.is_read
	 *
	 * @return the value of t_msg_base.is_read
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public Integer getIsRead() {
		return isRead;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_msg_base.is_read
	 *
	 * @param isRead the value for t_msg_base.is_read
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public void setIsRead(Integer isRead) {
		this.isRead = isRead;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_msg_base.create_time
	 *
	 * @return the value of t_msg_base.create_time
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_msg_base.create_time
	 *
	 * @param createTime the value for t_msg_base.create_time
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getHouseCard() {
		return houseCard;
	}

	public void setHouseCard(Integer houseCard) {
		this.houseCard = houseCard;
	}

	public Integer getIsSystemSend() {
		return isSystemSend;
	}

	public void setIsSystemSend(Integer isSystemSend) {
		this.isSystemSend = isSystemSend;
	}
}