package com.ziroom.minsu.entity.message;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

/**
 * 
 * <p>房源留言关联 实体</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author yd
 * @since 1.0
 * @version 1.0
 */
public class MsgHouseEntity extends BaseEntity{
    /**
	 * 序列id
	 */
	private static final long serialVersionUID = 4399180103629482317L;

	/**
	 * 主键
	 */
    private Integer id;

    /**
     * 业务编号
     */
    private String fid;

    /**
     * 房源fid
     */
    private String houseFid;

    /**
     * 房间fid
     */
    private String roomFid;

    /**
     * 床位fid
     */
    private String bedFid;

    /**
     * 房客uid
     */
    private String tenantUid;

    /**
     * 房东uid
     */
    private String landlordUid;

    /**
     * 出租类型 0：整租，1：合租，2：床位
     */
    private Integer rentWay;

    /**
     * 整条记录是否删除 默认0 (0：不删除 1 房东删除 2房客删除)
     */
    private Integer isDel;

    /**
     * 创建时间
     */
    private Date createTime;
    
    /**
     * 最后 修改时间
     */
    private Date imLastmodifyTime;
    

	/**
	 * @return the imLastmodifyTime
	 */
	public Date getImLastmodifyTime() {
		return imLastmodifyTime;
	}

	/**
	 * @param imLastmodifyTime the imLastmodifyTime to set
	 */
	public void setImLastmodifyTime(Date imLastmodifyTime) {
		this.imLastmodifyTime = imLastmodifyTime;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_house.id
     *
     * @return the value of t_msg_house.id
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_house.id
     *
     * @param id the value for t_msg_house.id
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_house.fid
     *
     * @return the value of t_msg_house.fid
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_house.fid
     *
     * @param fid the value for t_msg_house.fid
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_house.house_fid
     *
     * @return the value of t_msg_house.house_fid
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public String getHouseFid() {
        return houseFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_house.house_fid
     *
     * @param houseFid the value for t_msg_house.house_fid
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setHouseFid(String houseFid) {
        this.houseFid = houseFid == null ? null : houseFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_house.room_fid
     *
     * @return the value of t_msg_house.room_fid
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public String getRoomFid() {
        return roomFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_house.room_fid
     *
     * @param roomFid the value for t_msg_house.room_fid
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setRoomFid(String roomFid) {
        this.roomFid = roomFid == null ? null : roomFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_house.bed_fid
     *
     * @return the value of t_msg_house.bed_fid
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public String getBedFid() {
        return bedFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_house.bed_fid
     *
     * @param bedFid the value for t_msg_house.bed_fid
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setBedFid(String bedFid) {
        this.bedFid = bedFid == null ? null : bedFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_house.tenant_uid
     *
     * @return the value of t_msg_house.tenant_uid
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public String getTenantUid() {
        return tenantUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_house.tenant_uid
     *
     * @param tenantUid the value for t_msg_house.tenant_uid
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setTenantUid(String tenantUid) {
        this.tenantUid = tenantUid == null ? null : tenantUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_house.landlord_uid
     *
     * @return the value of t_msg_house.landlord_uid
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public String getLandlordUid() {
        return landlordUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_house.landlord_uid
     *
     * @param landlordUid the value for t_msg_house.landlord_uid
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setLandlordUid(String landlordUid) {
        this.landlordUid = landlordUid == null ? null : landlordUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_house.rent_way
     *
     * @return the value of t_msg_house.rent_way
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public Integer getRentWay() {
        return rentWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_house.rent_way
     *
     * @param rentWay the value for t_msg_house.rent_way
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setRentWay(Integer rentWay) {
        this.rentWay = rentWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_house.is_del
     *
     * @return the value of t_msg_house.is_del
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_house.is_del
     *
     * @param isDel the value for t_msg_house.is_del
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_house.create_time
     *
     * @return the value of t_msg_house.create_time
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_house.create_time
     *
     * @param createTime the value for t_msg_house.create_time
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}