package com.ziroom.minsu.entity.message;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;
/**
 * 
 * <p>留言标签自动回复实体</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author yd
 * @since 1.0
 * @version 1.0
 */
public class MsgLableEntity extends BaseEntity{
	/**
	 * 序列id
	 */
	private static final long serialVersionUID = -2846750900656353101L;

	/**
	 * 主键
	 */
	private Integer id;

	/**
	 * 业务编号
	 */
	private String fid;

	/**
	 * 留言关键词
	 */
	private String msgKey;

	/**
	 * 关键词所关联内容
	 */
	private String msgContent;

	/**
	 * 房东uid 如果适应于全局 house_fid 为0
	 */
	private String landlordFid;

	/**
	 * 房源fid  如果适应于全局 house_fid 为0 （也可以是其他类型标签的fid）
	 */
	private String houseFid;

	/**
	 * 是否适应于全局 默认 0（0：不适应全局 1：适应全局）
	 */
	private Integer isGlobal;

	/**
	 * 是否发布 默认0 发布（0：发布 1：不发布）
	 */
	private Integer isRelease;

	/**
	 * 创建时间
	 */
	private Date createTime;

	/**
	 * 最后修改时间
	 */
	private Date lastModifyDate;
	
	/**
	 * 标签类型 默认1 （1=房源标签）
	 */
	private Integer lableType;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_msg_lable.id
	 *
	 * @return the value of t_msg_lable.id
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_msg_lable.id
	 *
	 * @param id the value for t_msg_lable.id
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_msg_lable.fid
	 *
	 * @return the value of t_msg_lable.fid
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public String getFid() {
		return fid;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_msg_lable.fid
	 *
	 * @param fid the value for t_msg_lable.fid
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public void setFid(String fid) {
		this.fid = fid == null ? null : fid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_msg_lable.msg_key
	 *
	 * @return the value of t_msg_lable.msg_key
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public String getMsgKey() {
		return msgKey;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_msg_lable.msg_key
	 *
	 * @param msgKey the value for t_msg_lable.msg_key
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public void setMsgKey(String msgKey) {
		this.msgKey = msgKey == null ? null : msgKey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_msg_lable.msg_content
	 *
	 * @return the value of t_msg_lable.msg_content
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public String getMsgContent() {
		return msgContent;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_msg_lable.msg_content
	 *
	 * @param msgContent the value for t_msg_lable.msg_content
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public void setMsgContent(String msgContent) {
		this.msgContent = msgContent == null ? null : msgContent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_msg_lable.landlord_fid
	 *
	 * @return the value of t_msg_lable.landlord_fid
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public String getLandlordFid() {
		return landlordFid;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_msg_lable.landlord_fid
	 *
	 * @param landlordFid the value for t_msg_lable.landlord_fid
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public void setLandlordFid(String landlordFid) {
		this.landlordFid = landlordFid == null ? null : landlordFid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_msg_lable.house_fid
	 *
	 * @return the value of t_msg_lable.house_fid
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public String getHouseFid() {
		return houseFid;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_msg_lable.house_fid
	 *
	 * @param houseFid the value for t_msg_lable.house_fid
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public void setHouseFid(String houseFid) {
		this.houseFid = houseFid == null ? null : houseFid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_msg_lable.is_global
	 *
	 * @return the value of t_msg_lable.is_global
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public Integer getIsGlobal() {
		return isGlobal;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_msg_lable.is_global
	 *
	 * @param isGlobal the value for t_msg_lable.is_global
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public void setIsGlobal(Integer isGlobal) {
		this.isGlobal = isGlobal;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_msg_lable.is_release
	 *
	 * @return the value of t_msg_lable.is_release
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public Integer getIsRelease() {
		return isRelease;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_msg_lable.is_release
	 *
	 * @param isRelease the value for t_msg_lable.is_release
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public void setIsRelease(Integer isRelease) {
		this.isRelease = isRelease;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_msg_lable.create_time
	 *
	 * @return the value of t_msg_lable.create_time
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_msg_lable.create_time
	 *
	 * @param createTime the value for t_msg_lable.create_time
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_msg_lable.last_modify_date
	 *
	 * @return the value of t_msg_lable.last_modify_date
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public Date getLastModifyDate() {
		return lastModifyDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_msg_lable.last_modify_date
	 *
	 * @param lastModifyDate the value for t_msg_lable.last_modify_date
	 *
	 * @mbggenerated Sat Apr 16 12:39:23 CST 2016
	 */
	public void setLastModifyDate(Date lastModifyDate) {
		this.lastModifyDate = lastModifyDate;
	}

	public Integer getLableType() {
		return lableType;
	}

	public void setLableType(Integer lableType) {
		this.lableType = lableType;
	}
	
	
}