package com.ziroom.minsu.entity.message;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

/**
 * 
 * <p>房东设置自动回复实体/p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author yd
 * @since 1.0
 * @version 1.0
 */
public class MsgReplySetEntity extends BaseEntity{
    /**
	 * 序列id
	 */
	private static final long serialVersionUID = 2492357364642500761L;

	/**
	 * 主键
	 */
    private Integer id;

    /**
     * 业务编号
     */
    private String fid;

    /**
     * 房源fid
     */
    private String houseFid;

    /**
     * 房东uid
     */
    private String landlordUid;

    /**
     * 是否需要自动回复 默认0（0：自动回复  1：不自动回复）
     */
    private Integer isReply;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 最后修改时间
     */
    private Date lastModifyDate;
	/**
	 * 标签类型 默认1 （1=房源标签）
	 */
	private Integer lableType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_reply_set.id
     *
     * @return the value of t_msg_reply_set.id
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_reply_set.id
     *
     * @param id the value for t_msg_reply_set.id
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_reply_set.fid
     *
     * @return the value of t_msg_reply_set.fid
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_reply_set.fid
     *
     * @param fid the value for t_msg_reply_set.fid
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_reply_set.house_fid
     *
     * @return the value of t_msg_reply_set.house_fid
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public String getHouseFid() {
        return houseFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_reply_set.house_fid
     *
     * @param houseFid the value for t_msg_reply_set.house_fid
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setHouseFid(String houseFid) {
        this.houseFid = houseFid == null ? null : houseFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_reply_set.landlord_uid
     *
     * @return the value of t_msg_reply_set.landlord_uid
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public String getLandlordUid() {
        return landlordUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_reply_set.landlord_uid
     *
     * @param landlordUid the value for t_msg_reply_set.landlord_uid
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setLandlordUid(String landlordUid) {
        this.landlordUid = landlordUid == null ? null : landlordUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_reply_set.is_reply
     *
     * @return the value of t_msg_reply_set.is_reply
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public Integer getIsReply() {
        return isReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_reply_set.is_reply
     *
     * @param isReply the value for t_msg_reply_set.is_reply
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setIsReply(Integer isReply) {
        this.isReply = isReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_reply_set.create_time
     *
     * @return the value of t_msg_reply_set.create_time
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_reply_set.create_time
     *
     * @param createTime the value for t_msg_reply_set.create_time
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_reply_set.last_modify_date
     *
     * @return the value of t_msg_reply_set.last_modify_date
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_reply_set.last_modify_date
     *
     * @param lastModifyDate the value for t_msg_reply_set.last_modify_date
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

	public Integer getLableType() {
		return lableType;
	}

	public void setLableType(Integer lableType) {
		this.lableType = lableType;
	}
    
}