package com.ziroom.minsu.entity.message;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;


/**
 * 
 * <p>投诉建议表</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author yd
 * @since 1.0
 * @version 1.0
 */
public class SysComplainEntity extends BaseEntity {
    /**
	 * 序列id
	 */
	private static final long serialVersionUID = 8909210821767021846L;

	/***
	 * 自增id
	 */
    private Integer id;

    /***
     * 投诉者uid
     */
    private String complainUid;

    /**
     * 投诉者用户名
     */
    private String complainUsername;

    /**
     * 投诉者手机号
     */
    private String complainMphone;

    /**
     * 投诉内容
     */
    private String content;

    /**
     * 创建时间
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_complain.id
     *
     * @return the value of t_sys_complain.id
     *
     * @mbggenerated Wed May 04 11:46:33 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_complain.id
     *
     * @param id the value for t_sys_complain.id
     *
     * @mbggenerated Wed May 04 11:46:33 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_complain.complain_uid
     *
     * @return the value of t_sys_complain.complain_uid
     *
     * @mbggenerated Wed May 04 11:46:33 CST 2016
     */
    public String getComplainUid() {
        return complainUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_complain.complain_uid
     *
     * @param complainUid the value for t_sys_complain.complain_uid
     *
     * @mbggenerated Wed May 04 11:46:33 CST 2016
     */
    public void setComplainUid(String complainUid) {
        this.complainUid = complainUid == null ? null : complainUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_complain.complain_username
     *
     * @return the value of t_sys_complain.complain_username
     *
     * @mbggenerated Wed May 04 11:46:33 CST 2016
     */
    public String getComplainUsername() {
        return complainUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_complain.complain_username
     *
     * @param complainUsername the value for t_sys_complain.complain_username
     *
     * @mbggenerated Wed May 04 11:46:33 CST 2016
     */
    public void setComplainUsername(String complainUsername) {
        this.complainUsername = complainUsername == null ? null : complainUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_complain.complain_mphone
     *
     * @return the value of t_sys_complain.complain_mphone
     *
     * @mbggenerated Wed May 04 11:46:33 CST 2016
     */
    public String getComplainMphone() {
        return complainMphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_complain.complain_mphone
     *
     * @param complainMphone the value for t_sys_complain.complain_mphone
     *
     * @mbggenerated Wed May 04 11:46:33 CST 2016
     */
    public void setComplainMphone(String complainMphone) {
        this.complainMphone = complainMphone == null ? null : complainMphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_complain.content
     *
     * @return the value of t_sys_complain.content
     *
     * @mbggenerated Wed May 04 11:46:33 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_complain.content
     *
     * @param content the value for t_sys_complain.content
     *
     * @mbggenerated Wed May 04 11:46:33 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_complain.create_date
     *
     * @return the value of t_sys_complain.create_date
     *
     * @mbggenerated Wed May 04 11:46:33 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_complain.create_date
     *
     * @param createDate the value for t_sys_complain.create_date
     *
     * @mbggenerated Wed May 04 11:46:33 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}