package com.ziroom.minsu.entity.message;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

public class SysMsgEntity extends BaseEntity{
    /**
	 * 序列id
	 */
	private static final long serialVersionUID = -1206365781748567972L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_msg.id
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_msg.fid
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    private String fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_msg.msg_title
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    private String msgTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_msg.msg_content
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    private String msgContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_msg.msg_target_type
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    private Integer msgTargetType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_msg.msg_tmp_type
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    private Integer msgTmpType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_msg.msg_target_uid
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    private String msgTargetUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_msg.is_read
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    private Integer isRead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_msg.is_del
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_msg.create_time
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_msg.id
     *
     * @return the value of t_sys_msg.id
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_msg.id
     *
     * @param id the value for t_sys_msg.id
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_msg.fid
     *
     * @return the value of t_sys_msg.fid
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_msg.fid
     *
     * @param fid the value for t_sys_msg.fid
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_msg.msg_title
     *
     * @return the value of t_sys_msg.msg_title
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public String getMsgTitle() {
        return msgTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_msg.msg_title
     *
     * @param msgTitle the value for t_sys_msg.msg_title
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setMsgTitle(String msgTitle) {
        this.msgTitle = msgTitle == null ? null : msgTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_msg.msg_content
     *
     * @return the value of t_sys_msg.msg_content
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public String getMsgContent() {
        return msgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_msg.msg_content
     *
     * @param msgContent the value for t_sys_msg.msg_content
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setMsgContent(String msgContent) {
        this.msgContent = msgContent == null ? null : msgContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_msg.msg_target_type
     *
     * @return the value of t_sys_msg.msg_target_type
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public Integer getMsgTargetType() {
        return msgTargetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_msg.msg_target_type
     *
     * @param msgTargetType the value for t_sys_msg.msg_target_type
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setMsgTargetType(Integer msgTargetType) {
        this.msgTargetType = msgTargetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_msg.msg_tmp_type
     *
     * @return the value of t_sys_msg.msg_tmp_type
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public Integer getMsgTmpType() {
        return msgTmpType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_msg.msg_tmp_type
     *
     * @param msgTmpType the value for t_sys_msg.msg_tmp_type
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setMsgTmpType(Integer msgTmpType) {
        this.msgTmpType = msgTmpType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_msg.msg_target_uid
     *
     * @return the value of t_sys_msg.msg_target_uid
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public String getMsgTargetUid() {
        return msgTargetUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_msg.msg_target_uid
     *
     * @param msgTargetUid the value for t_sys_msg.msg_target_uid
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setMsgTargetUid(String msgTargetUid) {
        this.msgTargetUid = msgTargetUid == null ? null : msgTargetUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_msg.is_read
     *
     * @return the value of t_sys_msg.is_read
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public Integer getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_msg.is_read
     *
     * @param isRead the value for t_sys_msg.is_read
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setIsRead(Integer isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_msg.is_del
     *
     * @return the value of t_sys_msg.is_del
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_msg.is_del
     *
     * @param isDel the value for t_sys_msg.is_del
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_msg.create_time
     *
     * @return the value of t_sys_msg.create_time
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_msg.create_time
     *
     * @param createTime the value for t_sys_msg.create_time
     *
     * @mbggenerated Sat Apr 16 12:39:23 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}