package com.ziroom.minsu.entity.house;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

/**
 * 
 * <p>top房源操作日志</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author bushujie
 * @since 1.0
 * @version 1.0
 */
public class HouseTopLogEntity extends BaseEntity{
    /**
	 * 序列化id
	 */
	private static final long serialVersionUID = -3959765423620696242L;

	/**
     * 自增id
     * This field corresponds to the database column t_house_top_log.id
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    private Integer id;

    /**
     *逻辑fid
     * This field corresponds to the database column t_house_top_log.fid
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    private String fid;

    /**
     * top房源fid
     * This field corresponds to the database column t_house_top_log.house_top_fid
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    private String houseTopFid;

    /**
     * 操作类型 0：状态，1：顺序，2：内容
     * This field corresponds to the database column t_house_top_log.operate_type
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    private Integer operateType;

    /**
     * 原始值
     * This field corresponds to the database column t_house_top_log.from_state
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    private Integer fromState;

    /**
     * 改变值
     * This field corresponds to the database column t_house_top_log.to_state
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    private Integer toState;

    /**
     * 创建时间
     * This field corresponds to the database column t_house_top_log.create_date
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    private Date createDate;

    /**
     * 创建人fid
     * This field corresponds to the database column t_house_top_log.create_fid
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    private String createFid;

    /**
     * 创建人员工号
     * This field corresponds to the database column t_house_top_log.emp_code
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    private String empCode;

    /**
     * 创建人姓名
     * This field corresponds to the database column t_house_top_log.emp_name
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    private String empName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top_log.id
     *
     * @return the value of t_house_top_log.id
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top_log.id
     *
     * @param id the value for t_house_top_log.id
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top_log.fid
     *
     * @return the value of t_house_top_log.fid
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top_log.fid
     *
     * @param fid the value for t_house_top_log.fid
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top_log.house_top_fid
     *
     * @return the value of t_house_top_log.house_top_fid
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    public String getHouseTopFid() {
        return houseTopFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top_log.house_top_fid
     *
     * @param houseTopFid the value for t_house_top_log.house_top_fid
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    public void setHouseTopFid(String houseTopFid) {
        this.houseTopFid = houseTopFid == null ? null : houseTopFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top_log.operate_type
     *
     * @return the value of t_house_top_log.operate_type
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    public Integer getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top_log.operate_type
     *
     * @param operateType the value for t_house_top_log.operate_type
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    public void setOperateType(Integer operateType) {
        this.operateType = operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top_log.from_state
     *
     * @return the value of t_house_top_log.from_state
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    public Integer getFromState() {
        return fromState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top_log.from_state
     *
     * @param fromState the value for t_house_top_log.from_state
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    public void setFromState(Integer fromState) {
        this.fromState = fromState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top_log.to_state
     *
     * @return the value of t_house_top_log.to_state
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    public Integer getToState() {
        return toState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top_log.to_state
     *
     * @param toState the value for t_house_top_log.to_state
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    public void setToState(Integer toState) {
        this.toState = toState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top_log.create_date
     *
     * @return the value of t_house_top_log.create_date
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top_log.create_date
     *
     * @param createDate the value for t_house_top_log.create_date
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top_log.create_fid
     *
     * @return the value of t_house_top_log.create_fid
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    public String getCreateFid() {
        return createFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top_log.create_fid
     *
     * @param createFid the value for t_house_top_log.create_fid
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    public void setCreateFid(String createFid) {
        this.createFid = createFid == null ? null : createFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top_log.emp_code
     *
     * @return the value of t_house_top_log.emp_code
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    public String getEmpCode() {
        return empCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top_log.emp_code
     *
     * @param empCode the value for t_house_top_log.emp_code
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    public void setEmpCode(String empCode) {
        this.empCode = empCode == null ? null : empCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top_log.emp_name
     *
     * @return the value of t_house_top_log.emp_name
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top_log.emp_name
     *
     * @param empName the value for t_house_top_log.emp_name
     *
     * @mbggenerated Wed Mar 15 17:54:16 CST 2017
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }
}