package com.ziroom.minsu.entity.house;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

/**
 * 
 * <p>房源标签关系实体类</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author bushujie
 * @since 1.0
 * @version 1.0
 */
public class HouseTagEntity extends BaseEntity {
    /**
	 * 序列化id
	 */
	private static final long serialVersionUID = -4158090474215467676L;

	/**
     * 自增id
     * This field corresponds to the database column t_house_tag.id
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    private Integer id;

    /**
     * 逻辑fid
     * This field corresponds to the database column t_house_tag.fid
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    private String fid;

    /**
     * 房源fid
     * This field corresponds to the database column t_house_tag.house_base_fid
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    private String houseBaseFid;

    /**
     * 房间fid
     * This field corresponds to the database column t_house_tag.room_fid
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    private String roomFid;

    /**
     * 出租方式 0：整租，1：合租
     * This field corresponds to the database column t_house_tag.rent_way
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    private Integer rentWay;
    
    /**
     * 标签类型
     * This field corresponds to the database column t_house_tag.tag_type
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    private Integer tagType;

	/**
     * 标签fid
     * This field corresponds to the database column t_house_tag.tag_fid
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    private String tagFid;

    /**
     * 创建时间
     * This field corresponds to the database column t_house_tag.create_date
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    private Date createDate;

    /**
     * 最后更新时间
     * This field corresponds to the database column t_house_tag.last_modify_date
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    private Date lastModifyDate;

    /**
     * 是否删除 0：否，1：是
     * This field corresponds to the database column t_house_tag.is_del
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_tag.id
     *
     * @return the value of t_house_tag.id
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_tag.id
     *
     * @param id the value for t_house_tag.id
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_tag.fid
     *
     * @return the value of t_house_tag.fid
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_tag.fid
     *
     * @param fid the value for t_house_tag.fid
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_tag.house_base_fid
     *
     * @return the value of t_house_tag.house_base_fid
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    public String getHouseBaseFid() {
        return houseBaseFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_tag.house_base_fid
     *
     * @param houseBaseFid the value for t_house_tag.house_base_fid
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    public void setHouseBaseFid(String houseBaseFid) {
        this.houseBaseFid = houseBaseFid == null ? null : houseBaseFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_tag.room_fid
     *
     * @return the value of t_house_tag.room_fid
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    public String getRoomFid() {
        return roomFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_tag.room_fid
     *
     * @param roomFid the value for t_house_tag.room_fid
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    public void setRoomFid(String roomFid) {
        this.roomFid = roomFid == null ? null : roomFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_tag.rent_way
     *
     * @return the value of t_house_tag.rent_way
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    public Integer getRentWay() {
        return rentWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_tag.rent_way
     *
     * @param rentWay the value for t_house_tag.rent_way
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    public void setRentWay(Integer rentWay) {
        this.rentWay = rentWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_tag.tag_fid
     *
     * @return the value of t_house_tag.tag_fid
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    public String getTagFid() {
        return tagFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_tag.tag_fid
     *
     * @param tagFid the value for t_house_tag.tag_fid
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    public void setTagFid(String tagFid) {
        this.tagFid = tagFid == null ? null : tagFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_tag.create_date
     *
     * @return the value of t_house_tag.create_date
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_tag.create_date
     *
     * @param createDate the value for t_house_tag.create_date
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_tag.last_modify_date
     *
     * @return the value of t_house_tag.last_modify_date
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_tag.last_modify_date
     *
     * @param lastModifyDate the value for t_house_tag.last_modify_date
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_tag.is_del
     *
     * @return the value of t_house_tag.is_del
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_tag.is_del
     *
     * @param isDel the value for t_house_tag.is_del
     *
     * @mbggenerated Wed Mar 15 17:55:03 CST 2017
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
    
    /**
	 * @return the tagType
	 */
	public Integer getTagType() {
		return tagType;
	}

	/**
	 * @param tagType the tagType to set
	 */
	public void setTagType(Integer tagType) {
		this.tagType = tagType;
	}
}