package com.ziroom.minsu.entity.house;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;
/**
 * 
 * <p>房源跟进明细</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author bushujie
 * @since 1.0
 * @version 1.0
 */
public class HouseFollowLogEntity extends BaseEntity{
    /**
	 * 序列化id
	 */
	private static final long serialVersionUID = 827889542478799396L;

	/**
     * 主键id
     * This field corresponds to the database column t_house_follow_log.id
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    private Integer id;

    /**
     * 逻辑fid
     * This field corresponds to the database column t_house_follow_log.fid
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    private String fid;

    /**
     * 房源跟进主表fid
     * This field corresponds to the database column t_house_follow_log.follow_fid
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    private String followFid;

    /**
     * 初始状态
     * This field corresponds to the database column t_house_follow_log.from_status
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    private Integer fromStatus;

    /**
     * 改变后状态
     * This field corresponds to the database column t_house_follow_log.to_status
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    private Integer toStatus;
    
    /**
     * 跟进人类型 0:业务人员，1：房东
     */
    private Integer followUserType;

	/**
     * 跟进人fid
     * This field corresponds to the database column t_house_follow_log.follow_user_fid
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    private String followUserFid;

    /**
     * 跟进人员工编号
     * This field corresponds to the database column t_house_follow_log.follow_emp_code
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    private String followEmpCode;

    /**
     * 跟进人姓名
     * This field corresponds to the database column t_house_follow_log.follow_emp_name
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    private String followEmpName;

    /**
     * 跟新描述备注
     * This field corresponds to the database column t_house_follow_log.follow_desc
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    private String followDesc;

    /**
     * 创建时间
     * This field corresponds to the database column t_house_follow_log.create_date
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    private Date createDate;

    /**
     * 最新更新时间
     * This field corresponds to the database column t_house_follow_log.last_modify_date
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    private Date lastModifyDate;

    /**
     * 是否删除 0：否，1：是
     * This field corresponds to the database column t_house_follow_log.is_del
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_follow_log.id
     *
     * @return the value of t_house_follow_log.id
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_follow_log.id
     *
     * @param id the value for t_house_follow_log.id
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_follow_log.fid
     *
     * @return the value of t_house_follow_log.fid
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_follow_log.fid
     *
     * @param fid the value for t_house_follow_log.fid
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_follow_log.follow_fid
     *
     * @return the value of t_house_follow_log.follow_fid
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    public String getFollowFid() {
        return followFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_follow_log.follow_fid
     *
     * @param followFid the value for t_house_follow_log.follow_fid
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    public void setFollowFid(String followFid) {
        this.followFid = followFid == null ? null : followFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_follow_log.from_status
     *
     * @return the value of t_house_follow_log.from_status
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    public Integer getFromStatus() {
        return fromStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_follow_log.from_status
     *
     * @param fromStatus the value for t_house_follow_log.from_status
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    public void setFromStatus(Integer fromStatus) {
        this.fromStatus = fromStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_follow_log.to_status
     *
     * @return the value of t_house_follow_log.to_status
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    public Integer getToStatus() {
        return toStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_follow_log.to_status
     *
     * @param toStatus the value for t_house_follow_log.to_status
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    public void setToStatus(Integer toStatus) {
        this.toStatus = toStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_follow_log.follow_user_fid
     *
     * @return the value of t_house_follow_log.follow_user_fid
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    public String getFollowUserFid() {
        return followUserFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_follow_log.follow_user_fid
     *
     * @param followUserFid the value for t_house_follow_log.follow_user_fid
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    public void setFollowUserFid(String followUserFid) {
        this.followUserFid = followUserFid == null ? null : followUserFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_follow_log.follow_emp_code
     *
     * @return the value of t_house_follow_log.follow_emp_code
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    public String getFollowEmpCode() {
        return followEmpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_follow_log.follow_emp_code
     *
     * @param followEmpCode the value for t_house_follow_log.follow_emp_code
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    public void setFollowEmpCode(String followEmpCode) {
        this.followEmpCode = followEmpCode == null ? null : followEmpCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_follow_log.follow_emp_name
     *
     * @return the value of t_house_follow_log.follow_emp_name
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    public String getFollowEmpName() {
        return followEmpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_follow_log.follow_emp_name
     *
     * @param followEmpName the value for t_house_follow_log.follow_emp_name
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    public void setFollowEmpName(String followEmpName) {
        this.followEmpName = followEmpName == null ? null : followEmpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_follow_log.follow_desc
     *
     * @return the value of t_house_follow_log.follow_desc
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    public String getFollowDesc() {
        return followDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_follow_log.follow_desc
     *
     * @param followDesc the value for t_house_follow_log.follow_desc
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    public void setFollowDesc(String followDesc) {
        this.followDesc = followDesc == null ? null : followDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_follow_log.create_date
     *
     * @return the value of t_house_follow_log.create_date
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_follow_log.create_date
     *
     * @param createDate the value for t_house_follow_log.create_date
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_follow_log.last_modify_date
     *
     * @return the value of t_house_follow_log.last_modify_date
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_follow_log.last_modify_date
     *
     * @param lastModifyDate the value for t_house_follow_log.last_modify_date
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_follow_log.is_del
     *
     * @return the value of t_house_follow_log.is_del
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_follow_log.is_del
     *
     * @param isDel the value for t_house_follow_log.is_del
     *
     * @mbggenerated Wed Feb 22 14:56:16 CST 2017
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
    
    /**
	 * @return the followUserType
	 */
	public Integer getFollowUserType() {
		return followUserType;
	}

	/**
	 * @param followUserType the followUserType to set
	 */
	public void setFollowUserType(Integer followUserType) {
		this.followUserType = followUserType;
	}
}