package com.ziroom.minsu.entity.house;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

/**
 * 
 * <p>top房源类目实体类</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author bushujie
 * @since 1.0
 * @version 1.0
 */
public class HouseTopColumnEntity extends BaseEntity{
    /**
	 * 序列化id
	 */
	private static final long serialVersionUID = -7309758334785233156L;

	/**
     * 自增id
     * This field corresponds to the database column t_house_top_column.id
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    private Integer id;

    /**
     * 逻辑fid
     * This field corresponds to the database column t_house_top_column.fid
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    private String fid;

    /**
     * top房源fid
     * This field corresponds to the database column t_house_top_column.house_top_fid
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    private String houseTopFid;

    /**
     * 条目类型 101：亮点标题,102：描述标题,103：文章标题,104：标题1,105：标题2，201：亮点文本，202：文章文本，203：图片注释，204：文章出处，301：图片，401：视频，501：音频
     * This field corresponds to the database column t_house_top_column.column_type
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    private Integer columnType;

    /**
     * 条目样式 101：左对齐，102：右对齐，103：中对齐
     * This field corresponds to the database column t_house_top_column.column_style
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    private Integer columnStyle;

    /**
     * 条目排序号
     * This field corresponds to the database column t_house_top_column.column_sort
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    private Integer columnSort;

    /**
     * 图片访问基础地址
     * This field corresponds to the database column t_house_top_column.pic_base_url
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    private String picBaseUrl;

    /**
     * 图片后缀
     * This field corresponds to the database column t_house_top_column.pic_suffix
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    private String picSuffix;

    /**
     * 图片服务器唯一标示
     * This field corresponds to the database column t_house_top_column.pic_server_uuid
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    private String picServerUuid;

    /**
     * 创建时间
     * This field corresponds to the database column t_house_top_column.create_date
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    private Date createDate;

    /**
     * 最后更新时间
     * This field corresponds to the database column t_house_top_column.last_modify_date
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    private Date lastModifyDate;

    /**
     * 是否删除 0：否，1：是
     * This field corresponds to the database column t_house_top_column.is_del
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    private Integer isDel;

    /**
     * 条目内容
     * This field corresponds to the database column t_house_top_column.column_content
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    private String columnContent;
    
    /**
     * 图片宽度
     */
    private Integer width;
    
    /**
     * 图片高度
     */
    private Integer hight;
    
    public Integer getWidth() {
		return width;
	}

	public Integer getHight() {
		return hight;
	}

	public void setWidth(Integer width) {
		this.width = width;
	}

	public void setHight(Integer hight) {
		this.hight = hight;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top_column.id
     *
     * @return the value of t_house_top_column.id
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top_column.id
     *
     * @param id the value for t_house_top_column.id
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top_column.fid
     *
     * @return the value of t_house_top_column.fid
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top_column.fid
     *
     * @param fid the value for t_house_top_column.fid
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top_column.house_top_fid
     *
     * @return the value of t_house_top_column.house_top_fid
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    public String getHouseTopFid() {
        return houseTopFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top_column.house_top_fid
     *
     * @param houseTopFid the value for t_house_top_column.house_top_fid
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    public void setHouseTopFid(String houseTopFid) {
        this.houseTopFid = houseTopFid == null ? null : houseTopFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top_column.column_type
     *
     * @return the value of t_house_top_column.column_type
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    public Integer getColumnType() {
        return columnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top_column.column_type
     *
     * @param columnType the value for t_house_top_column.column_type
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    public void setColumnType(Integer columnType) {
        this.columnType = columnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top_column.column_style
     *
     * @return the value of t_house_top_column.column_style
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    public Integer getColumnStyle() {
        return columnStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top_column.column_style
     *
     * @param columnStyle the value for t_house_top_column.column_style
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    public void setColumnStyle(Integer columnStyle) {
        this.columnStyle = columnStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top_column.column_sort
     *
     * @return the value of t_house_top_column.column_sort
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    public Integer getColumnSort() {
        return columnSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top_column.column_sort
     *
     * @param columnSort the value for t_house_top_column.column_sort
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    public void setColumnSort(Integer columnSort) {
        this.columnSort = columnSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top_column.pic_base_url
     *
     * @return the value of t_house_top_column.pic_base_url
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    public String getPicBaseUrl() {
        return picBaseUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top_column.pic_base_url
     *
     * @param picBaseUrl the value for t_house_top_column.pic_base_url
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    public void setPicBaseUrl(String picBaseUrl) {
        this.picBaseUrl = picBaseUrl == null ? null : picBaseUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top_column.pic_suffix
     *
     * @return the value of t_house_top_column.pic_suffix
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    public String getPicSuffix() {
        return picSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top_column.pic_suffix
     *
     * @param picSuffix the value for t_house_top_column.pic_suffix
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    public void setPicSuffix(String picSuffix) {
        this.picSuffix = picSuffix == null ? null : picSuffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top_column.pic_server_uuid
     *
     * @return the value of t_house_top_column.pic_server_uuid
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    public String getPicServerUuid() {
        return picServerUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top_column.pic_server_uuid
     *
     * @param picServerUuid the value for t_house_top_column.pic_server_uuid
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    public void setPicServerUuid(String picServerUuid) {
        this.picServerUuid = picServerUuid == null ? null : picServerUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top_column.create_date
     *
     * @return the value of t_house_top_column.create_date
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top_column.create_date
     *
     * @param createDate the value for t_house_top_column.create_date
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top_column.last_modify_date
     *
     * @return the value of t_house_top_column.last_modify_date
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top_column.last_modify_date
     *
     * @param lastModifyDate the value for t_house_top_column.last_modify_date
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top_column.is_del
     *
     * @return the value of t_house_top_column.is_del
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top_column.is_del
     *
     * @param isDel the value for t_house_top_column.is_del
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top_column.column_content
     *
     * @return the value of t_house_top_column.column_content
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    public String getColumnContent() {
        return columnContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top_column.column_content
     *
     * @param columnContent the value for t_house_top_column.column_content
     *
     * @mbggenerated Wed Mar 15 17:52:01 CST 2017
     */
    public void setColumnContent(String columnContent) {
        this.columnContent = columnContent == null ? null : columnContent.trim();
    }
}