package com.ziroom.minsu.entity.house;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

/**
 * 
 * <p>房源商机信息来源表实体类</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author bushujie
 * @since 1.0
 * @version 1.0
 */
public class HouseBusinessSourceEntity extends BaseEntity{
    /**
	 * 序列化id
	 */
	private static final long serialVersionUID = -6234480852758087963L;

	/**
     * 主键自增id
     * This field corresponds to the database column t_house_business_source.id
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    private Integer id;

    /**
     * 逻辑fid
     * This field corresponds to the database column t_house_business_source.fid
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    private String fid;

    /**
     * 商机主表fid
     * This field corresponds to the database column t_house_business_source.business_fid
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    private String businessFid;

    /**
     * 商机来源 0：地推扩展，1：房东自住发布
     * This field corresponds to the database column t_house_business_source.busniess_source
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    private Integer busniessSource;

    /**
     * 是否在作业范围 0：否，1：是
     * This field corresponds to the database column t_house_business_source.is_job_area
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    private Integer isJobArea;

    /**
     * 商机来源网址
     * This field corresponds to the database column t_house_business_source.source_url
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    private String sourceUrl;

    /**
     * 评价数量
     * This field corresponds to the database column t_house_business_source.evaluate_num
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    private Integer evaluateNum;

    /**
     * 评价分
     * This field corresponds to the database column t_house_business_source.house_grade
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    private Double houseGrade;

    /**
     * 创建人fid
     * This field corresponds to the database column t_house_business_source.create_fid
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    private String createFid;

    /**
     * 创建时间
     * This field corresponds to the database column t_house_business_source.create_date
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    private Date createDate;

    /**
     * 最后修改时间
     * This field corresponds to the database column t_house_business_source.last_modify_date
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    private Date lastModifyDate;

    /**
     * 是否删除 0：否，1：是
     * This field corresponds to the database column t_house_business_source.is_del
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_business_source.id
     *
     * @return the value of t_house_business_source.id
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_business_source.id
     *
     * @param id the value for t_house_business_source.id
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }


    /**
	 * @return the fid
	 */
	public String getFid() {
		return fid;
	}

	/**
	 * @param fid the fid to set
	 */
	public void setFid(String fid) {
		this.fid = fid;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_business_source.business_fid
     *
     * @return the value of t_house_business_source.business_fid
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    public String getBusinessFid() {
        return businessFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_business_source.business_fid
     *
     * @param businessFid the value for t_house_business_source.business_fid
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    public void setBusinessFid(String businessFid) {
        this.businessFid = businessFid == null ? null : businessFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_business_source.busniess_source
     *
     * @return the value of t_house_business_source.busniess_source
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    public Integer getBusniessSource() {
        return busniessSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_business_source.busniess_source
     *
     * @param busniessSource the value for t_house_business_source.busniess_source
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    public void setBusniessSource(Integer busniessSource) {
        this.busniessSource = busniessSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_business_source.is_job_area
     *
     * @return the value of t_house_business_source.is_job_area
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    public Integer getIsJobArea() {
        return isJobArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_business_source.is_job_area
     *
     * @param isJobArea the value for t_house_business_source.is_job_area
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    public void setIsJobArea(Integer isJobArea) {
        this.isJobArea = isJobArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_business_source.source_url
     *
     * @return the value of t_house_business_source.source_url
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    public String getSourceUrl() {
        return sourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_business_source.source_url
     *
     * @param sourceUrl the value for t_house_business_source.source_url
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl == null ? null : sourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_business_source.evaluate_num
     *
     * @return the value of t_house_business_source.evaluate_num
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    public Integer getEvaluateNum() {
        return evaluateNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_business_source.evaluate_num
     *
     * @param evaluateNum the value for t_house_business_source.evaluate_num
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    public void setEvaluateNum(Integer evaluateNum) {
        this.evaluateNum = evaluateNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_business_source.house_grade
     *
     * @return the value of t_house_business_source.house_grade
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    public Double getHouseGrade() {
        return houseGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_business_source.house_grade
     *
     * @param houseGrade the value for t_house_business_source.house_grade
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    public void setHouseGrade(Double houseGrade) {
        this.houseGrade = houseGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_business_source.create_fid
     *
     * @return the value of t_house_business_source.create_fid
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    public String getCreateFid() {
        return createFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_business_source.create_fid
     *
     * @param createFid the value for t_house_business_source.create_fid
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    public void setCreateFid(String createFid) {
        this.createFid = createFid == null ? null : createFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_business_source.create_date
     *
     * @return the value of t_house_business_source.create_date
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_business_source.create_date
     *
     * @param createDate the value for t_house_business_source.create_date
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_business_source.last_modify_date
     *
     * @return the value of t_house_business_source.last_modify_date
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_business_source.last_modify_date
     *
     * @param lastModifyDate the value for t_house_business_source.last_modify_date
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_business_source.is_del
     *
     * @return the value of t_house_business_source.is_del
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_business_source.is_del
     *
     * @param isDel the value for t_house_business_source.is_del
     *
     * @mbggenerated Tue Jul 05 16:35:34 CST 2016
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}