package com.ziroom.minsu.entity.house;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

/**
 * 
 * <p>房源业务锁表</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author bushujie
 * @since 1.0
 * @version 1.0
 */
public class HouseLockEntity extends BaseEntity{
    /**
	 * 序列化id
	 */
	private static final long serialVersionUID = 5575651484406853333L;

	/**
     * 自增id
     * This field corresponds to the database column t_house_lock.id
     *
     * @mbggenerated Wed Feb 22 15:20:52 CST 2017
     */
    private Integer id;

    /**
     * 逻辑fid
     * This field corresponds to the database column t_house_lock.fid
     *
     * @mbggenerated Wed Feb 22 15:20:52 CST 2017
     */
    private String fid;

    /**
     * 锁业务code
     * This field corresponds to the database column t_house_lock.house_lock_code
     *
     * @mbggenerated Wed Feb 22 15:20:52 CST 2017
     */
    private String houseLockCode;

    /**
     * 上锁业务fid
     * This field corresponds to the database column t_house_lock.locker_fid
     *
     * @mbggenerated Wed Feb 22 15:20:52 CST 2017
     */
    private String lockerFid;

    /**
     * 被锁者业务fid
     * This field corresponds to the database column t_house_lock.locked_fid
     *
     * @mbggenerated Wed Feb 22 15:20:52 CST 2017
     */
    private String lockedFid;

    /**
     * 锁失效时间
     * This field corresponds to the database column t_house_lock.lock_fail_date
     *
     * @mbggenerated Wed Feb 22 15:20:52 CST 2017
     */
    private String lockFailDate;

    /**
     * 创建人fid
     * This field corresponds to the database column t_house_lock.create_fid
     *
     * @mbggenerated Wed Feb 22 15:20:52 CST 2017
     */
    private String createFid;

    /**
     * 创建时间
     * This field corresponds to the database column t_house_lock.create_date
     *
     * @mbggenerated Wed Feb 22 15:20:52 CST 2017
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_lock.id
     *
     * @return the value of t_house_lock.id
     *
     * @mbggenerated Wed Feb 22 15:20:52 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_lock.id
     *
     * @param id the value for t_house_lock.id
     *
     * @mbggenerated Wed Feb 22 15:20:52 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_lock.fid
     *
     * @return the value of t_house_lock.fid
     *
     * @mbggenerated Wed Feb 22 15:20:52 CST 2017
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_lock.fid
     *
     * @param fid the value for t_house_lock.fid
     *
     * @mbggenerated Wed Feb 22 15:20:52 CST 2017
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_lock.house_lock_code
     *
     * @return the value of t_house_lock.house_lock_code
     *
     * @mbggenerated Wed Feb 22 15:20:52 CST 2017
     */
    public String getHouseLockCode() {
        return houseLockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_lock.house_lock_code
     *
     * @param houseLockCode the value for t_house_lock.house_lock_code
     *
     * @mbggenerated Wed Feb 22 15:20:52 CST 2017
     */
    public void setHouseLockCode(String houseLockCode) {
        this.houseLockCode = houseLockCode == null ? null : houseLockCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_lock.locker_fid
     *
     * @return the value of t_house_lock.locker_fid
     *
     * @mbggenerated Wed Feb 22 15:20:52 CST 2017
     */
    public String getLockerFid() {
        return lockerFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_lock.locker_fid
     *
     * @param lockerFid the value for t_house_lock.locker_fid
     *
     * @mbggenerated Wed Feb 22 15:20:52 CST 2017
     */
    public void setLockerFid(String lockerFid) {
        this.lockerFid = lockerFid == null ? null : lockerFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_lock.locked_fid
     *
     * @return the value of t_house_lock.locked_fid
     *
     * @mbggenerated Wed Feb 22 15:20:52 CST 2017
     */
    public String getLockedFid() {
        return lockedFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_lock.locked_fid
     *
     * @param lockedFid the value for t_house_lock.locked_fid
     *
     * @mbggenerated Wed Feb 22 15:20:52 CST 2017
     */
    public void setLockedFid(String lockedFid) {
        this.lockedFid = lockedFid == null ? null : lockedFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_lock.lock_fail_date
     *
     * @return the value of t_house_lock.lock_fail_date
     *
     * @mbggenerated Wed Feb 22 15:20:52 CST 2017
     */
    public String getLockFailDate() {
        return lockFailDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_lock.lock_fail_date
     *
     * @param lockFailDate the value for t_house_lock.lock_fail_date
     *
     * @mbggenerated Wed Feb 22 15:20:52 CST 2017
     */
    public void setLockFailDate(String lockFailDate) {
        this.lockFailDate = lockFailDate == null ? null : lockFailDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_lock.create_fid
     *
     * @return the value of t_house_lock.create_fid
     *
     * @mbggenerated Wed Feb 22 15:20:52 CST 2017
     */
    public String getCreateFid() {
        return createFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_lock.create_fid
     *
     * @param createFid the value for t_house_lock.create_fid
     *
     * @mbggenerated Wed Feb 22 15:20:52 CST 2017
     */
    public void setCreateFid(String createFid) {
        this.createFid = createFid == null ? null : createFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_lock.create_date
     *
     * @return the value of t_house_lock.create_date
     *
     * @mbggenerated Wed Feb 22 15:20:52 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_lock.create_date
     *
     * @param createDate the value for t_house_lock.create_date
     *
     * @mbggenerated Wed Feb 22 15:20:52 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}