package com.ziroom.minsu.entity.house;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

 /**
  * 
  * <p>top房源实体类</p>
  * 
  * <PRE>
  * <BR>	修改记录
  * <BR>-----------------------------------------------
  * <BR>	修改日期			修改人			修改内容
  * </PRE>
  * 
  * @author bushujie
  * @since 1.0
  * @version 1.0
  */
public class HouseTopEntity extends BaseEntity{
    /**
	 * 序列化id
	 */
	private static final long serialVersionUID = 5542735646523907920L;

	/**
     * 自增id
     * This field corresponds to the database column t_house_top.id
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    private Integer id;

    /**
     * 逻辑fid
     * This field corresponds to the database column t_house_top.fid
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    private String fid;

    /**
     * 房源fid
     * This field corresponds to the database column t_house_top.house_base_fid
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    private String houseBaseFid;

    /**
     * 房间fid
     * This field corresponds to the database column t_house_top.room_fid
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    private String roomFid;

    /**
     * 出租方式 0：否，1：是
     * This field corresponds to the database column t_house_top.rent_way
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    private Integer rentWay;

    /**
     * 房源top状态 0：新建，1：上线，2：下线
     * This field corresponds to the database column t_house_top.top_status
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    private Integer topStatus;

    /**
     * 房源top排序
     * This field corresponds to the database column t_house_top.top_sort
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    private Integer topSort;

    /**
     * top房源分享标题
     * This field corresponds to the database column t_house_top.top_share_title
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    private String topShareTitle;

    /**
     * top房源标题图片地址
     * This field corresponds to the database column t_house_top.top_title_pic
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    private String topTitlePic;

    /**
     * top房源详情页中部图片地址
     * This field corresponds to the database column t_house_top.top_middle_pic
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    private String topMiddlePic;

    /**
     * top房源标题
     * This field corresponds to the database column t_house_top.top_title
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    private String topTitle;

    /**
     * 创建人fid
     * This field corresponds to the database column t_house_top.create_fid
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    private String createFid;

    /**
     * 创建时间
     * This field corresponds to the database column t_house_top.create_date
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    private Date createDate;

    /**
     * 最后更新时间
     * This field corresponds to the database column t_house_top.last_modify_date
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    private Date lastModifyDate;

    /**
     * 是否删除 0：否，1：是
     * This field corresponds to the database column t_house_top.is_del
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top.id
     *
     * @return the value of t_house_top.id
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top.id
     *
     * @param id the value for t_house_top.id
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top.fid
     *
     * @return the value of t_house_top.fid
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top.fid
     *
     * @param fid the value for t_house_top.fid
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top.house_base_fid
     *
     * @return the value of t_house_top.house_base_fid
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public String getHouseBaseFid() {
        return houseBaseFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top.house_base_fid
     *
     * @param houseBaseFid the value for t_house_top.house_base_fid
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public void setHouseBaseFid(String houseBaseFid) {
        this.houseBaseFid = houseBaseFid == null ? null : houseBaseFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top.room_fid
     *
     * @return the value of t_house_top.room_fid
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public String getRoomFid() {
        return roomFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top.room_fid
     *
     * @param roomFid the value for t_house_top.room_fid
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public void setRoomFid(String roomFid) {
        this.roomFid = roomFid == null ? null : roomFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top.rent_way
     *
     * @return the value of t_house_top.rent_way
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public Integer getRentWay() {
        return rentWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top.rent_way
     *
     * @param rentWay the value for t_house_top.rent_way
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public void setRentWay(Integer rentWay) {
        this.rentWay = rentWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top.top_status
     *
     * @return the value of t_house_top.top_status
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public Integer getTopStatus() {
        return topStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top.top_status
     *
     * @param topStatus the value for t_house_top.top_status
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public void setTopStatus(Integer topStatus) {
        this.topStatus = topStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top.top_sort
     *
     * @return the value of t_house_top.top_sort
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public Integer getTopSort() {
        return topSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top.top_sort
     *
     * @param topSort the value for t_house_top.top_sort
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public void setTopSort(Integer topSort) {
        this.topSort = topSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top.top_share_title
     *
     * @return the value of t_house_top.top_share_title
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public String getTopShareTitle() {
        return topShareTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top.top_share_title
     *
     * @param topShareTitle the value for t_house_top.top_share_title
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public void setTopShareTitle(String topShareTitle) {
        this.topShareTitle = topShareTitle == null ? null : topShareTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top.top_title_pic
     *
     * @return the value of t_house_top.top_title_pic
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public String getTopTitlePic() {
        return topTitlePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top.top_title_pic
     *
     * @param topTitlePic the value for t_house_top.top_title_pic
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public void setTopTitlePic(String topTitlePic) {
        this.topTitlePic = topTitlePic == null ? null : topTitlePic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top.top_middle_pic
     *
     * @return the value of t_house_top.top_middle_pic
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public String getTopMiddlePic() {
        return topMiddlePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top.top_middle_pic
     *
     * @param topMiddlePic the value for t_house_top.top_middle_pic
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public void setTopMiddlePic(String topMiddlePic) {
        this.topMiddlePic = topMiddlePic == null ? null : topMiddlePic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top.top_title
     *
     * @return the value of t_house_top.top_title
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public String getTopTitle() {
        return topTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top.top_title
     *
     * @param topTitle the value for t_house_top.top_title
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public void setTopTitle(String topTitle) {
        this.topTitle = topTitle == null ? null : topTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top.create_fid
     *
     * @return the value of t_house_top.create_fid
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public String getCreateFid() {
        return createFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top.create_fid
     *
     * @param createFid the value for t_house_top.create_fid
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public void setCreateFid(String createFid) {
        this.createFid = createFid == null ? null : createFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top.create_date
     *
     * @return the value of t_house_top.create_date
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top.create_date
     *
     * @param createDate the value for t_house_top.create_date
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top.last_modify_date
     *
     * @return the value of t_house_top.last_modify_date
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top.last_modify_date
     *
     * @param lastModifyDate the value for t_house_top.last_modify_date
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_top.is_del
     *
     * @return the value of t_house_top.is_del
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_top.is_del
     *
     * @param isDel the value for t_house_top.is_del
     *
     * @mbggenerated Wed Mar 15 17:25:28 CST 2017
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}