package com.ziroom.minsu.entity.house;

import java.util.Date;

import com.asura.framework.base.entity.BaseEntity;

 /**
  * 
  * <p>房源相关统计信息</p>
  * 
  * <PRE>
  * <BR>	修改记录
  * <BR>-----------------------------------------------
  * <BR>	修改日期			修改人			修改内容
  * </PRE>
  * 
  * @author bushujie
  * @since 1.0
  * @version 1.0
  */
public class HouseStatisticsMsgEntity extends BaseEntity {
    /**
	 * 序列化id
	 */
	private static final long serialVersionUID = -4862080946430521010L;

	/**
     * 主键id自增
     * This field corresponds to the database column t_house_statistics_msg.id
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    private Integer id;

    /**
     *逻辑fid
     * This field corresponds to the database column t_house_statistics_msg.fid
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    private String fid;

    /**
     * 房源fid
     * This field corresponds to the database column t_house_statistics_msg.house_base_fid
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    private String houseBaseFid;

    /**
     *房间fid
     * This field corresponds to the database column t_house_statistics_msg.room_fid
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    private String roomFid;

    /**
     * 床铺fid
     * This field corresponds to the database column t_house_statistics_msg.bed_fid
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    private String bedFid;

    /**
     *房源浏览量
     * This field corresponds to the database column t_house_statistics_msg.house_pv
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    private Integer housePv;

    /**
     * 出租方式
     * This field corresponds to the database column t_house_statistics_msg.rentWay
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    private Integer rentWay;

    /**
     *创建人fid
     * This field corresponds to the database column t_house_statistics_msg.create_fid
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    private String createFid;

    /**
     * 创建时间
     * This field corresponds to the database column t_house_statistics_msg.create_date
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    private Date createDate;

    /**
     * 最后更新时间
     * This field corresponds to the database column t_house_statistics_msg.last_modify_date
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    private Date lastModifyDate;

    /**
     * 是否删除
     * This field corresponds to the database column t_house_statistics_msg.is_del
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_statistics_msg.id
     *
     * @return the value of t_house_statistics_msg.id
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_statistics_msg.id
     *
     * @param id the value for t_house_statistics_msg.id
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_statistics_msg.fid
     *
     * @return the value of t_house_statistics_msg.fid
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_statistics_msg.fid
     *
     * @param fid the value for t_house_statistics_msg.fid
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_statistics_msg.house_base_fid
     *
     * @return the value of t_house_statistics_msg.house_base_fid
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    public String getHouseBaseFid() {
        return houseBaseFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_statistics_msg.house_base_fid
     *
     * @param houseBaseFid the value for t_house_statistics_msg.house_base_fid
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    public void setHouseBaseFid(String houseBaseFid) {
        this.houseBaseFid = houseBaseFid == null ? null : houseBaseFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_statistics_msg.room_fid
     *
     * @return the value of t_house_statistics_msg.room_fid
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    public String getRoomFid() {
        return roomFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_statistics_msg.room_fid
     *
     * @param roomFid the value for t_house_statistics_msg.room_fid
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    public void setRoomFid(String roomFid) {
        this.roomFid = roomFid == null ? null : roomFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_statistics_msg.bed_fid
     *
     * @return the value of t_house_statistics_msg.bed_fid
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    public String getBedFid() {
        return bedFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_statistics_msg.bed_fid
     *
     * @param bedFid the value for t_house_statistics_msg.bed_fid
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    public void setBedFid(String bedFid) {
        this.bedFid = bedFid == null ? null : bedFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_statistics_msg.house_pv
     *
     * @return the value of t_house_statistics_msg.house_pv
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    public Integer getHousePv() {
        return housePv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_statistics_msg.house_pv
     *
     * @param housePv the value for t_house_statistics_msg.house_pv
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    public void setHousePv(Integer housePv) {
        this.housePv = housePv;
    }

    /**
	 * @return the rentWay
	 */
	public Integer getRentWay() {
		return rentWay;
	}

	/**
	 * @param rentWay the rentWay to set
	 */
	public void setRentWay(Integer rentWay) {
		this.rentWay = rentWay;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_statistics_msg.create_fid
     *
     * @return the value of t_house_statistics_msg.create_fid
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    public String getCreateFid() {
        return createFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_statistics_msg.create_fid
     *
     * @param createFid the value for t_house_statistics_msg.create_fid
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    public void setCreateFid(String createFid) {
        this.createFid = createFid == null ? null : createFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_statistics_msg.create_date
     *
     * @return the value of t_house_statistics_msg.create_date
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_statistics_msg.create_date
     *
     * @param createDate the value for t_house_statistics_msg.create_date
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_statistics_msg.last_modify_date
     *
     * @return the value of t_house_statistics_msg.last_modify_date
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_statistics_msg.last_modify_date
     *
     * @param lastModifyDate the value for t_house_statistics_msg.last_modify_date
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_statistics_msg.is_del
     *
     * @return the value of t_house_statistics_msg.is_del
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_statistics_msg.is_del
     *
     * @param isDel the value for t_house_statistics_msg.is_del
     *
     * @mbggenerated Sun May 15 00:39:30 CST 2016
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}