package com.ziroom.minsu.entity.house;

import com.asura.framework.base.entity.BaseEntity;

import java.util.Date;
/**
 * 
 * <p>今夜特价实体类</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author bushujie
 * @since 1.0
 * @version 1.0
 */
public class TonightDiscountEntity extends BaseEntity{
    /**
	 * 序列化id
	 */
	private static final long serialVersionUID = -633787727961970562L;

	/**
     * 自增id
     * This field corresponds to the database column t_house_tonight_discount.id
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    private Integer id;

    /**
     * 逻辑fid
     * This field corresponds to the database column t_house_tonight_discount.fid
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    private String fid;

    /**
     * 房源fid
     * This field corresponds to the database column t_house_tonight_discount.house_fid
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    private String houseFid;

    /**
     * 房间fid
     * This field corresponds to the database column t_house_tonight_discount.room_fid
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    private String roomFid;

    /**
     * 出租方式 0：整租，1：合租
     * This field corresponds to the database column t_house_tonight_discount.rent_way
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    private Integer rentWay;

    /**
     * 折扣值
     * This field corresponds to the database column t_house_tonight_discount.discount
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    private Double discount;

    /**
     * 设置来源1，房东设置；2，后台设置
     * This field corresponds to the database column t_house_tonight_discount.discount_source
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    private Integer discountSource;

    /**
     * 今夜特价开始时间
     */
    private Date startTime;

    /**
     * 今夜特价结束时间
     */
    private Date endTime;

    /**
     * 创建时间
     * This field corresponds to the database column t_house_tonight_discount.create_date
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    private Date createDate;

    /**
     * 创建人uid
     * This field corresponds to the database column t_house_tonight_discount.create_uid
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    private String createUid;

    /**
     * 生效日期
     * This field corresponds to the database column t_house_tonight_discount.discount_date
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    private Date discountDate;

    /**
     * 最后更新时间
     * This field corresponds to the database column t_house_tonight_discount.last_modify_date
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    private Date lastModifyDate;

    /**
     * 修改人uid
     * This field corresponds to the database column t_house_tonight_discount.last_modify_uid
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    private String lastModifyUid;

    /**
     * 是否删除
     * This field corresponds to the database column t_house_tonight_discount.is_del
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    private Integer isDel;

    public Date getStartTime() {
        return startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_tonight_discount.id
     *
     * @return the value of t_house_tonight_discount.id
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_tonight_discount.id
     *
     * @param id the value for t_house_tonight_discount.id
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_tonight_discount.fid
     *
     * @return the value of t_house_tonight_discount.fid
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_tonight_discount.fid
     *
     * @param fid the value for t_house_tonight_discount.fid
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_tonight_discount.house_fid
     *
     * @return the value of t_house_tonight_discount.house_fid
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    public String getHouseFid() {
        return houseFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_tonight_discount.house_fid
     *
     * @param houseFid the value for t_house_tonight_discount.house_fid
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    public void setHouseFid(String houseFid) {
        this.houseFid = houseFid == null ? null : houseFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_tonight_discount.room_fid
     *
     * @return the value of t_house_tonight_discount.room_fid
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    public String getRoomFid() {
        return roomFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_tonight_discount.room_fid
     *
     * @param roomFid the value for t_house_tonight_discount.room_fid
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    public void setRoomFid(String roomFid) {
        this.roomFid = roomFid == null ? null : roomFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_tonight_discount.rent_way
     *
     * @return the value of t_house_tonight_discount.rent_way
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    public Integer getRentWay() {
        return rentWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_tonight_discount.rent_way
     *
     * @param rentWay the value for t_house_tonight_discount.rent_way
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    public void setRentWay(Integer rentWay) {
        this.rentWay = rentWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_tonight_discount.discount
     *
     * @return the value of t_house_tonight_discount.discount
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    public Double getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_tonight_discount.discount
     *
     * @param discount the value for t_house_tonight_discount.discount
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_tonight_discount.discount_source
     *
     * @return the value of t_house_tonight_discount.discount_source
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    public Integer getDiscountSource() {
        return discountSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_tonight_discount.discount_source
     *
     * @param discountSource the value for t_house_tonight_discount.discount_source
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    public void setDiscountSource(Integer discountSource) {
        this.discountSource = discountSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_tonight_discount.create_date
     *
     * @return the value of t_house_tonight_discount.create_date
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_tonight_discount.create_date
     *
     * @param createDate the value for t_house_tonight_discount.create_date
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_tonight_discount.create_uid
     *
     * @return the value of t_house_tonight_discount.create_uid
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    public String getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_tonight_discount.create_uid
     *
     * @param createUid the value for t_house_tonight_discount.create_uid
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    public void setCreateUid(String createUid) {
        this.createUid = createUid == null ? null : createUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_tonight_discount.discount_date
     *
     * @return the value of t_house_tonight_discount.discount_date
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    public Date getDiscountDate() {
        return discountDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_tonight_discount.discount_date
     *
     * @param discountDate the value for t_house_tonight_discount.discount_date
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    public void setDiscountDate(Date discountDate) {
        this.discountDate = discountDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_tonight_discount.last_modify_date
     *
     * @return the value of t_house_tonight_discount.last_modify_date
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_tonight_discount.last_modify_date
     *
     * @param lastModifyDate the value for t_house_tonight_discount.last_modify_date
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_tonight_discount.last_modify_uid
     *
     * @return the value of t_house_tonight_discount.last_modify_uid
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    public String getLastModifyUid() {
        return lastModifyUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_tonight_discount.last_modify_uid
     *
     * @param lastModifyUid the value for t_house_tonight_discount.last_modify_uid
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    public void setLastModifyUid(String lastModifyUid) {
        this.lastModifyUid = lastModifyUid == null ? null : lastModifyUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_tonight_discount.is_del
     *
     * @return the value of t_house_tonight_discount.is_del
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_tonight_discount.is_del
     *
     * @param isDel the value for t_house_tonight_discount.is_del
     *
     * @mbggenerated Wed May 10 15:33:32 CST 2017
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}